### PR TITLE
Validate nested constructs

### LINKED ISSUE #3031: opt: dEQP-VK.graphicsfuzz.discard-continue-return
This test fails. To reproduce: 

```
spirv-opt -O -o temp.spv *.spv
spirv-val temp.spv
```

[discard-continue-return.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/3833315/discard-continue-return.zip)

### PR DESCRIPTION
**Pull request by alan-baker**
Validate the spec rule:
> when a construct contains another header block, it also contains that header’s corresponding merge block if that merge block is reachable in the CFG

Fixes #3031 

Identified problems in block merging and inlining. Block merging will no longer merge a continue target. Inlining a single block loop will not modify the continue target. Had to fix up many invalid tests.

### CODE REVIEW

**Comment by alan-baker** [comment]
This PR was tested against CTS and found issues with several tests. Those are being addressed separately, but this PR should not be integrated into CTS until those changes are made.

File: source/opt/inline_pass.cpp [hunk 1]
```diff
@@ -291,13 +290,9 @@ bool InlinePass::GenInlineCode(
   // at the end of the first block.  First determine if the caller is in a
   // single block loop.  We'll wait to move the OpLoopMerge until the end
   // of the regular inlining logic, and only if necessary.
-  bool caller_is_single_block_loop = false;
```
Comment (dneto0) [inline source/opt/inline_pass.cpp]: The comment immediately above this calls out the single-block loop case.
But what's really salient about the situation is that the caller is in the loop header, and the callee has multiple blocks.
You should update the comment to reflect the more accurate/salient aspect of the situation.

File: test/val/val_cfg_test.cpp [hunk 2]
```diff
@@ -2038,12 +2039,9 @@ TEST_P(ValidateCFG,
 }
 
 TEST_P(ValidateCFG, ContinueTargetCanBeMergeBlockForNestedStructureGood) {
```
Comment (dneto0) [inline test/val/val_cfg_test.cpp]: Please update the test name.  Shouldn't say Good unconditionally at the end.
