### PR TITLE
[val] Add extra context to error messages.

### LINKED ISSUE #670: spirv-val has inconsistent location reporting for errors
Running spirv-val on a particular module I was looking at I got this:

```
info: 507: Duplicate non-aggregate type declarations are not allowed. Opcode: 32
error: 3095: The result pointer storage class and base pointer storage class in OpAccessChain do not match.
```

507 being the opcode index, and 3095 being the word count offset of the parameter in the OpAccessChain.

The latter I don't think is useful directly, but being able to identify the particular word is nice. I'd suggest that instead the opcode index should always be used since it's easy to look up in the spirv-dis output (apart from the comments at the start with the header, it's just the line number), and instead the error should be displayed something like `error: filename.spv:574:1: ...` similar to line:column numbers in compiler outputs.

As an aside, I didn't realise it was the opcode index until I looked at the source, although that's partly because one of them wasn't so I dismissed that possibility. It might be a good idea to explicitly call that out, and add an option to spirv-dis to display the opcode indices on the left-hand side similar to how it can display the word offset in hex as a comment on the right.

----

Extra bonus points if you used the disassembly to display context on what exactly is wrong, like this mockup:

```                                                                                 
output_dump.spv:507: info: Duplicate non-aggregate type declarations are not allowed.
%_ptr_Uniform_float_0 = OpTypePointer Uniform %float
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

output_dump.spv:431: note: First type declaration here
%_ptr_Uniform_float = OpTypePointer Uniform %float
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

output_dump.spv:574:1: error: The result pointer storage class and base pointer storage class in OpAccessChain do not match.
      %25242 = OpAccessChain %_ptr_Uniform_v4float %_entryPointOutput %uint_1
                             ~~~~~~~~~~~~~~~~~~~~~ ^^^^^^^^^^^^^^^^^^^^^^^^^^

output_dump.spv:422: note: %_ptr_Uniform_v4float declared here
%_ptr_Uniform_v4float = OpTypePointer Uniform %v4float
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

output_dump.spv:422: note: %_entryPointOutput declared here
%_entryPointOutput = OpVariable %_ptr_Output_VS_OUTPUT_0 Output
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


1 warning generated.
1 error generated.
```

### PR DESCRIPTION
**Pull request by dj2**
This CL extends the error messages produced by the validator to output the
disassembly of the errored line.

The validation_id messages have also been updated to print the line number of
the error instead of the word number. Note, the error number is from the start
of the SPIR-V, it does not include any headers printed in the disassembled code.

Fixes #670, #1581

### CODE REVIEW

**Comment by dj2** [comment]
Please let me know if this is on the right track.

For issue 1581 this would output:
```
error: line 735: OpStore Pointer <id> '137' is not a logical pointer.
  %obj = OpPhi %_ptr_Function_bool %493 %549 %493 %550 %493 %546 ; 0x00000014
```

and for the example provided in 670 it would output:
```
error: line 1: TypeInt cannot appear before the memory model instruction
  %uint = OpTypeInt 32 0 ; 0x00000014
```

I think for 670 we may also want to change the <id> '137' to output <id> '137[obj]' or whatever the getIdName() string is for that object.

**Comment by dj2** [comment]
Found the issue, I need to run cmake with -DSPIRV_BUILD_COMPRESSION=ON to match the bots.

**Comment by dj2** [comment]
Will need to do a bit of work to make this build/run with the markv stuff. Will ping when the CL is read for review again.

**Comment by dneto0** [comment]
FYI.  The Markv decoder case is the sticky one because the uncompressed form of the SPIR-V module is not anywhere in memory.  See https://github.com/KhronosGroup/SPIRV-Tools/pull/1221#issuecomment-358789690 for @atgoo's suggestion on how to resolve this.

File: source/val/validation_state.cpp [hunk 1]
```diff
@@ -829,4 +845,20 @@ const std::vector<uint32_t>& ValidationState_t::FunctionEntryPoints(
...
+  return Disassemble(c_inst.words, c_inst.num_words);
+}
+
+std::string ValidationState_t::Disassemble(const uint32_t* words,
+                                           uint16_t num_words) const {
+  uint32_t disassembly_options = SPV_BINARY_TO_TEXT_OPTION_NO_HEADER |
+                                 SPV_BINARY_TO_TEXT_OPTION_FRIENDLY_NAMES |
+                                 SPV_BINARY_TO_TEXT_OPTION_SHOW_BYTE_OFFSET;
+
+  return spvtools::spvInstructionBinaryToText(context()->target_env, words,
```
Comment (dneto0) [inline source/val/validation_state.cpp]: Let's fix this in a subsequent CL, but this can be wrong for things like 
`OpConstant %int 42` because you need type info to know that %int is actually an int, and therefore how to interpret the "42" word.  (E.g. compare with a floating point constant.)
A second bad case is OpSwitch where again you need type info to know how many words the literals are.

Interestingly, the spv_parsed_instruction_t has the necessary info.

An actually correct solution would generalize the disassembler so that you pass in the entire binary in and ask only for a specific instruction. It would have to run through the entire binary to collect the type info, and only accumulate string output for the requested instruction (by index).

And yeah, I messed this up on my original attempt. It was quick and dirty and only 95% right.

File: source/diagnostic.h [hunk 2]
```diff
@@ -30,8 +30,12 @@ class DiagnosticStream {
  public:
   DiagnosticStream(spv_position_t position,
```
Comment (dneto0) [inline source/diagnostic.h]: Given that there are so many times you call this constructor with an empty string value for the disassembled_instruction member, I would have probably made a second constructor.

File: test/c_interface_test.cpp [hunk 3]
```diff
@@ -194,8 +194,10 @@ TEST(CInterface, SpecifyConsumerNullDiagnosticForValidating) {
         // TODO(antiagainst): what validation reports is not a word offset here.
         // It is inconsistent with diassembler. Should be fixed.
         EXPECT_EQ(1u, position.index);
-        EXPECT_STREQ("Nop cannot appear before the memory model instruction",
-                     message);
+        EXPECT_STREQ(
+            "Nop cannot appear before the memory model instruction\n"
+            "  OpNop ; 0x00000014\n",
```
Comment (dneto0) [inline test/c_interface_test.cpp]: Let's lose the byte offset since it's a lie in the general case.

File: tools/io.h [hunk 4]
```diff
@@ -39,7 +39,10 @@ bool ReadFile(const char* filename, const char* mode, std::vector<T>* data) {
       }
     } else {
       if (sizeof(T) != 1 && (ftell(fp) % sizeof(T))) {
-        fprintf(stderr, "error: corrupted word found in file '%s'\n", filename);
+        fprintf(
+            stderr,
+            "error: file size should be a multiple of %ld; file '%s' corrput\n",
```
Comment (dneto0) [inline tools/io.h]: Spelling of "corrupt"

File: source/val/validation_state.cpp [hunk 5]
```diff
@@ -829,4 +845,20 @@ const std::vector<uint32_t>& ValidationState_t::FunctionEntryPoints(
...
+std::string ValidationState_t::Disassemble(const Instruction& inst) const {
+  const spv_parsed_instruction_t& c_inst(inst.c_inst());
+  return Disassemble(c_inst.words, c_inst.num_words);
+}
+
+std::string ValidationState_t::Disassemble(const uint32_t* words,
+                                           uint16_t num_words) const {
+  uint32_t disassembly_options = SPV_BINARY_TO_TEXT_OPTION_NO_HEADER |
+                                 SPV_BINARY_TO_TEXT_OPTION_FRIENDLY_NAMES |
+                                 SPV_BINARY_TO_TEXT_OPTION_SHOW_BYTE_OFFSET;
```
[the remark this answers is not in the document]
Comment (dneto0) [reply source/val/validation_state.cpp]: Actually, if the strategy changes to have the whole binary in hand, and you really do know which instruction position (index) it is, then you should keep this show-byte-offset because then it's the truth and extra information the user could use.

File: source/diagnostic.cpp [hunk 6]
```diff
@@ -71,6 +71,7 @@ DiagnosticStream::DiagnosticStream(DiagnosticStream&& other)
     : stream_(),
       position_(other.position_),
       consumer_(other.consumer_),
+      disassembled_instruction_(other.disassembled_instruction_),
```
[the remark this answers is not in the document]
Comment (dj2) [reply source/diagnostic.cpp]: done

File: source/diagnostic.h (hunk 2 above)
Comment (dj2) [reply source/diagnostic.h]: I'm on the fence for this one. It makes it a lot clearer where we don't have a disassembled_instruction and, hopefully, would make it harder to add a missing one in the future. It's also possible, some of the fields I have as blank could have values, like bad header and a couple others.

File: source/val/validation_state.cpp [hunk 7]
```diff
@@ -142,9 +142,13 @@ bool IsInstructionInLayoutSection(ModuleLayoutSection layout, SpvOp op) {
 }  // anonymous namespace
 
 ValidationState_t::ValidationState_t(const spv_const_context ctx,
-                                     const spv_const_validator_options opt)
+                                     const spv_const_validator_options opt,
+                                     const uint32_t* words,
```
[the remark this answers is not in the document]
Comment (dj2) [reply source/val/validation_state.cpp]: Yea, realized this when I hit the bots and figured out they use different flags. Going to try to work out Markv and will ping when the updates are done.

File: source/val/validation_state.cpp (hunk 5 above)
[the remark this answers is not in the document]
Comment (dj2) [reply source/val/validation_state.cpp]: Removed for now. It was always outputting 0x14 and I couldn't figure out where it came from. We can always put back later if desired.

File: source/val/validation_state.cpp (hunk 1 above)
Comment (dj2) [reply source/val/validation_state.cpp]: So, is the problem that sometimes it would decompile one of:
```
OpConstant %int 42
OpConstant %int 42.0
```
because it doesn't know if it's a float or an int?

File: test/c_interface_test.cpp (hunk 3 above)
Comment (dj2) [reply test/c_interface_test.cpp]: done

File: tools/io.h (hunk 4 above)
Comment (dj2) [reply tools/io.h]: done

**Comment by dj2** [comment]
PTAL. I changed the Markv code to do validation at the beginning of encode and the end of decode so we should have the full binary available. This removes the need to create a ValidationState in the MarkvDecode constructor.

File: source/val/validation_state.cpp (hunk 1 above)
Comment (dneto0) [reply source/val/validation_state.cpp]: Yes, that's one problem.

Another is with 

`OpSwitch %value %default  12 %label0  43 %label1 52 %label3`

The %value and literals are supposed to be integer scalars.  But you need to see the OpTypeInt to know how many bits wide it is, and therefore how many words wide it is.  That's needed to know how to decode the words for the cases.  E.g. 6 words could be 3 pairs of (32-bit literal, target-id) or 2 pairs of (64bit literal, target-id)

**Comment by dj2** [comment]
Rebased, will see if AppVeyor is happy now.

File: source/diagnostic.h (hunk 2 above)
Comment (dneto0) [reply source/diagnostic.h]: > would make it harder to add a missing one in the future.  

That's a good argument.

File: source/val/validation_state.cpp [hunk 8]
```diff
@@ -254,9 +258,19 @@ bool ValidationState_t::IsOpcodeInCurrentLayoutSection(SpvOp op) {
...
 DiagnosticStream ValidationState_t::diag(spv_result_t error_code) const {
+  return diag(error_code, instruction_counter_);
+}
+
+DiagnosticStream ValidationState_t::diag(spv_result_t error_code,
+                                         int instruction_counter) const {
+  std::string disassembly;
+  if (instruction_counter >= 0 && static_cast<size_t>(instruction_counter) <=
+                                      ordered_instructions_.size()) {
+    disassembly = Disassemble(ordered_instructions_[instruction_counter - 1]);
```
Comment (dneto0) [inline source/val/validation_state.cpp]: This produces the right output in almost all situations.
Corner cases where it does not are where type info from prior instructions are required to correctly parse:  e.g. OpConstnat %int ....  and also OpSwitch 

That can wait for a future PR.  I'll file an issue for this.

Comment (dneto0) [reply source/val/validation_state.cpp]: I filed #1627 but the results are better than I expected. :-)
