### PR TITLE
spirv-fuzz: Avoid the type manager when looking for struct types

### LINKED ISSUE #3947: spirv-fuzz: TransformationReplaceParametersWithStruct chooses wrong struct type
If isomorphic structs are present then this transformation can pick the wrong struct type.  It should be changed so as to not depend on the type manager.

### PR DESCRIPTION
**Pull request by afd**
Fixes #3947.

### CODE REVIEW

File: source/fuzz/fuzzer_util.cpp [hunk 1]
```diff
@@ -418,6 +418,8 @@ bool IsValidAndWellFormed(const opt::IRContext* ir_context,
                           spv_validator_options validator_options,
                           MessageConsumer consumer) {
   if (!IsValid(ir_context, validator_options, consumer)) {
+    // Expression to dump |ir_context| to /data/temp/shader.spv:
+    //    DumpShader(ir_context, "/data/temp/shader.spv")
```
Comment (paulthomson) [inline source/fuzz/fuzzer_util.cpp:422]: Debug code to remove?

**Review by paulthomson — APPROVED** [review]

File: source/fuzz/fuzzer_util.cpp (hunk 1 above)
Comment (afd) [reply source/fuzz/fuzzer_util.cpp:422]: I actually decided to include this as it's very useful (especially as someone new to the project wouldn't know about DumpShader).
