### PR TITLE
Fix explicit layout validation on ptr type

### LINKED ISSUE #6028: Explicit Layout Check reports false error for logical structs with phyiscal pointer members.
The recent change in #6012 leads to spirv-val reporting a validation error that appears to be incorrect:
```
error: line 143: Invalid explicit layout decorations on type for operand '19[%_ptr_Function_LinkedNode]'
  %20 = OpVariable %_ptr_Function_LinkedNode Function
```

Full SPIRV is attached below. Basically, `LinkedNode` is:
```
%LinkedNode = OpTypeStruct %float %_ptr_PhysicalStorageBuffer_float 
```

Note that `LinkedNode` itself has no explicit layout decorations, although the second member of this struct is a physical pointer. The layout decoration on the physical pointer shouldn't be treated as layout decorations for the `LinkedNode` type.

Full SPIRV:

```
; SPIR-V
; Version: 1.5
; Generator: Khronos; 40
; Bound: 131
; Schema: 0
OpCapability PhysicalStorageBufferAddresses
OpCapability Shader
OpExtension "SPV_KHR_non_semantic_info"
OpExtension "SPV_KHR_physical_storage_buffer"
OpExtension "SPV_KHR_relaxed_extended_instruction"
OpExtension "SPV_KHR_storage_buffer_storage_class"
%2 = OpExtInstImport "NonSemantic.Shader.DebugInfo.100"
OpMemoryModel PhysicalStorageBuffer64 GLSL450
OpEntryPoint GLCompute %computeMain "main" %outputBuffer %Constants
OpExecutionMode %computeMain LocalSize 1 1 1

; Debug Information
%1 = OpString "//TEST(compute, vulkan):SIMPLE(filecheck=SPV): -stage compute -entry computeMain -target spirv -emit-spirv-directly -g2
//DISABLE_TEST(compute, vulkan):SIMPLE(filecheck=SPV): -stage compute -entry computeMain -target spirv -emit-spirv-directly -g2 -zero-initialize

// This test is to check if DebugTypePointer is emitted when \"-g2\" option is used

//TEST_INPUT:ubuffer(data=[0], stride=4):out,name=outputBuffer
RWStructuredBuffer<float> outputBuffer;

//SPV:OpExtension \"SPV_KHR_relaxed_extended_instruction\"
//SPV: [[STRING_float:%[1-9][0-9]*]] = OpString \"float\"
//SPV: [[STRING_pValue:%[1-9][0-9]*]] = OpString \"pValue\"
//SPV: [[STRING_LinkedNode:%[1-9][0-9]*]] = OpString \"LinkedNode{{.*}}\"
//SPV: [[STRING_pNext:%[1-9][0-9]*]] = OpString \"pNext\"

struct LinkedNode
{
    float value;

    //SPV: [[TYPE_float:%[1-9][0-9]*]] = OpExtInst %void %{{[0-9]*}} DebugTypeBasic [[STRING_float]]
    //SPV: [[TYPE_float_ptr:%[1-9][0-9]*]] = OpExtInst %void %{{[0-9]*}} DebugTypePointer [[TYPE_float]]
    //SPV: DebugTypeMember [[STRING_pValue]] [[TYPE_float_ptr]]
    float *pValue;

    // \"MEMBER_pNext\" hasn't been declared yet, but OpExtInstWithForwardRefs requires at least one of these \"forward declared ID\".
    //SPV: [[FORWARD_LinkedNode:%[1-9][0-9]*]] = OpExtInstWithForwardRefsKHR %void %{{[0-9]*}} DebugTypeComposite [[STRING_LinkedNode]] {{.*}} [[MEMBER_pNext:%[1-9][0-9]*]]
    //SPV: [[TYPE_pLinkedNode:%[1-9][0-9]*]] = OpExtInst %void %{{[0-9]*}} DebugTypePointer [[FORWARD_LinkedNode]]
    //SPV: [[MEMBER_pNext]] = {{.*}} DebugTypeMember [[STRING_pNext]] [[TYPE_pLinkedNode]]
    LinkedNode *pNext;
};

//SPV:  OpExtInst %void %{{[0-9]*}} DebugTypeComposite [[STRING_LinkedNode]] {{.*}} [[MEMBER_pNext]]

float test(LinkedNode *pNode)
{
    LinkedNode *pNodeNext = pNode->pNext;
    return *(pNode->pValue) + pNodeNext->value;
}

cbuffer Constants
{
    LinkedNode *head;
};

[numthreads(1,1,1)]
void computeMain()
{
    LinkedNode node; // required to emit DebugTypeXXX
    outputBuffer[0] = test(head);
}

"
%5 = OpString "D:\\git_repo\\slang\\tests\\spirv\\debug-type-pointer.slang"
OpSource Unknown 1
%24 = OpString "computeMain"
%30 = OpString "slangc"
%31 = OpString "-target spirv  -I \"D:\\git_repo\\slang\\build\\Debug\\bin\" -matrix-layout-column-major -stage compute -entry computeMain -g2"
%37 = OpString "float"
%42 = OpString "value"
%48 = OpString "pValue"
%53 = OpString "LinkedNode_natural"
%58 = OpString "pNext"
%64 = OpString "LinkedNode"
%66 = OpString "node"
%96 = OpString "test"
%102 = OpString "pNode"
%110 = OpString "pNodeNext"
OpName %LinkedNode "LinkedNode"                     ; id %14
OpMemberName %LinkedNode 0 "value"
OpMemberName %LinkedNode 0 "pValue"
OpMemberName %LinkedNode 0 "pNext"
OpName %node "node"                                 ; id %65
OpName %RWStructuredBuffer "RWStructuredBuffer"     ; id %76
OpName %outputBuffer "outputBuffer"                 ; id %79
OpName %SLANG_ParameterGroup_Constants_std140 "SLANG_ParameterGroup_Constants_std140"   ; id %80
OpMemberName %SLANG_ParameterGroup_Constants_std140 0 "head"
OpName %Constants "Constants"                       ; id %82
OpName %pNode "pNode"                               ; id %89
OpName %pNode_0 "pNode"                             ; id %101
OpName %pNodeNext "pNodeNext"                       ; id %109
OpName %pNodeNext_0 "pNodeNext"                     ; id %116
OpName %test "test"                                 ; id %87
OpName %computeMain "computeMain"                   ; id %11
OpName %LinkedNode_natural "LinkedNode_natural"     ; id %17
OpMemberName %LinkedNode_natural 0 "value"
OpMemberName %LinkedNode_natural 1 "pValue"
OpMemberName %LinkedNode_natural 2 "pNext"

; Annotations
OpDecorate %_ptr_PhysicalStorageBuffer_float ArrayStride 4
OpDecorate %_ptr_PhysicalStorageBuffer_LinkedNode_natural ArrayStride 24
OpDecorate %_runtimearr_float ArrayStride 4
OpDecorate %RWStructuredBuffer Block
OpMemberDecorate %RWStructuredBuffer 0 Offset 0
OpDecorate %outputBuffer Binding 0
OpDecorate %outputBuffer DescriptorSet 0
OpDecorate %SLANG_ParameterGroup_Constants_std140 Block
OpMemberDecorate %SLANG_ParameterGroup_Constants_std140 0 Offset 0
OpDecorate %Constants Binding 1
OpDecorate %Constants DescriptorSet 0
OpDecorate %pNode Aliased
OpDecorate %92 AliasedPointer
OpDecorate %93 AliasedPointer
OpDecorate %_ptr_PhysicalStorageBuffer_18 ArrayStride 8
OpDecorate %_ptr_PhysicalStorageBuffer__ptr_PhysicalStorageBuffer_float ArrayStride 8
OpMemberDecorate %LinkedNode_natural 0 Offset 0
OpMemberDecorate %LinkedNode_natural 1 Offset 8
OpMemberDecorate %LinkedNode_natural 2 Offset 16

; Types, variables and constants
%void = OpTypeVoid
%4 = OpExtInst %void %2 DebugSource %5 %1
%uint = OpTypeInt 32 0
%uint_11 = OpConstant %uint 11
%uint_5 = OpConstant %uint 5
%uint_100 = OpConstant %uint 100
%10 = OpExtInst %void %2 DebugCompilationUnit %uint_100 %uint_5 %4 %uint_11
%12 = OpTypeFunction %void
%float = OpTypeFloat 32
%_ptr_PhysicalStorageBuffer_float = OpTypePointer PhysicalStorageBuffer %float  ; ArrayStride 4
OpTypeForwardPointer %_ptr_PhysicalStorageBuffer_LinkedNode_natural PhysicalStorageBuffer
%LinkedNode = OpTypeStruct %float %_ptr_PhysicalStorageBuffer_float %_ptr_PhysicalStorageBuffer_LinkedNode_natural
%_ptr_Function_LinkedNode = OpTypePointer Function %LinkedNode
%uint_0 = OpConstant %uint 0
%21 = OpExtInst %void %2 DebugTypeFunction %uint_0 %void
%uint_45 = OpConstant %uint 45
%uint_6 = OpConstant %uint 6
%23 = OpExtInst %void %2 DebugFunction %24 %21 %4 %uint_45 %uint_6 %10 %24 %uint_0 %uint_45
%29 = OpExtInst %void %2 DebugEntryPoint %23 %10 %30 %31
%uint_47 = OpConstant %uint 47
%uint_32 = OpConstant %uint 32
%uint_3 = OpConstant %uint 3
%uint_131072 = OpConstant %uint 131072
%36 = OpExtInst %void %2 DebugTypeBasic %37 %uint_32 %uint_3 %uint_131072
%uint_15 = OpConstant %uint 15
%uint_8 = OpConstant %uint 8
%41 = OpExtInst %void %2 DebugTypeMember %42 %36 %4 %uint_15 %uint_8 %uint_0 %uint_32 %uint_0
%uint_5349 = OpConstant %uint 5349
%45 = OpExtInst %void %2 DebugTypePointer %36 %uint_5349 %uint_131072
%uint_64 = OpConstant %uint 64
%47 = OpExtInst %void %2 DebugTypeMember %48 %45 %4 %uint_15 %uint_8 %uint_64 %uint_64 %uint_0
%50 = OpExtInst %void %2 DebugTypeMember %42 %36 %4 %uint_0 %uint_0 %uint_0 %uint_32 %uint_0
%51 = OpExtInst %void %2 DebugTypeMember %48 %45 %4 %uint_0 %uint_0 %uint_64 %uint_64 %uint_0
%uint_1 = OpConstant %uint 1
%uint_192 = OpConstant %uint 192
%52 = OpExtInstWithForwardRefsKHR %void %2 DebugTypeComposite %53 %uint_1 %4 %uint_0 %uint_0 %10 %53 %uint_192 %uint_131072 %50 %51 %57
%56 = OpExtInst %void %2 DebugTypePointer %52 %uint_5349 %uint_131072
%uint_128 = OpConstant %uint 128
%57 = OpExtInst %void %2 DebugTypeMember %58 %56 %4 %uint_0 %uint_0 %uint_128 %uint_64 %uint_0
%60 = OpExtInst %void %2 DebugTypeComposite %53 %uint_1 %4 %uint_0 %uint_0 %10 %53 %uint_192 %uint_131072 %50 %51 %57
%61 = OpExtInst %void %2 DebugTypePointer %60 %uint_5349 %uint_131072
%62 = OpExtInst %void %2 DebugTypeMember %58 %61 %4 %uint_15 %uint_8 %uint_128 %uint_64 %uint_0
%63 = OpExtInst %void %2 DebugTypeComposite %64 %uint_1 %4 %uint_15 %uint_8 %10 %64 %uint_192 %uint_131072 %41 %47 %62
%uint_16 = OpConstant %uint 16
%node = OpExtInst %void %2 DebugLocalVariable %66 %63 %4 %uint_47 %uint_16 %23 %uint_0
%68 = OpExtInst %void %2 DebugExpression
%uint_48 = OpConstant %uint 48
%int = OpTypeInt 32 1
%int_0 = OpConstant %int 0
%_ptr_StorageBuffer_float = OpTypePointer StorageBuffer %float
%_runtimearr_float = OpTypeRuntimeArray %float      ; ArrayStride 4
%RWStructuredBuffer = OpTypeStruct %_runtimearr_float   ; Block
%_ptr_StorageBuffer_RWStructuredBuffer = OpTypePointer StorageBuffer %RWStructuredBuffer
%SLANG_ParameterGroup_Constants_std140 = OpTypeStruct %_ptr_PhysicalStorageBuffer_LinkedNode_natural    ; Block
%_ptr_Uniform_SLANG_ParameterGroup_Constants_std140 = OpTypePointer Uniform %SLANG_ParameterGroup_Constants_std140
%_ptr_Uniform_18 = OpTypePointer Uniform %_ptr_PhysicalStorageBuffer_LinkedNode_natural
%88 = OpTypeFunction %float %_ptr_PhysicalStorageBuffer_LinkedNode_natural
%_ptr_Function_18 = OpTypePointer Function %_ptr_PhysicalStorageBuffer_LinkedNode_natural
%94 = OpExtInst %void %2 DebugTypeFunction %uint_0 %void
%uint_33 = OpConstant %uint 33
%uint_7 = OpConstant %uint 7
%95 = OpExtInst %void %2 DebugFunction %96 %94 %4 %uint_33 %uint_7 %10 %96 %uint_0 %uint_33
%pNode_0 = OpExtInst %void %2 DebugLocalVariable %102 %61 %4 %uint_33 %uint_7 %95 %uint_0 %uint_0
%uint_35 = OpConstant %uint 35
%uint_17 = OpConstant %uint 17
%pNodeNext = OpExtInst %void %2 DebugLocalVariable %110 %61 %4 %uint_35 %uint_17 %95 %uint_0
%int_2 = OpConstant %int 2
%_ptr_PhysicalStorageBuffer_18 = OpTypePointer PhysicalStorageBuffer %_ptr_PhysicalStorageBuffer_LinkedNode_natural     ; ArrayStride 8
%uint_36 = OpConstant %uint 36
%int_1 = OpConstant %int 1
%_ptr_PhysicalStorageBuffer__ptr_PhysicalStorageBuffer_float = OpTypePointer PhysicalStorageBuffer %_ptr_PhysicalStorageBuffer_float    ; ArrayStride 8
%LinkedNode_natural = OpTypeStruct %float %_ptr_PhysicalStorageBuffer_float %_ptr_PhysicalStorageBuffer_LinkedNode_natural
%_ptr_PhysicalStorageBuffer_LinkedNode_natural = OpTypePointer PhysicalStorageBuffer %LinkedNode_natural    ; ArrayStride 24
%outputBuffer = OpVariable %_ptr_StorageBuffer_RWStructuredBuffer StorageBuffer                             ; Binding 0, DescriptorSet 0
%Constants = OpVariable %_ptr_Uniform_SLANG_ParameterGroup_Constants_std140 Uniform                         ; Binding 1, DescriptorSet 0

; Function computeMain
%computeMain = OpFunction %void None %12
%13 = OpLabel
%20 = OpVariable %_ptr_Function_LinkedNode Function
%27 = OpExtInst %void %2 DebugFunctionDefinition %23 %computeMain
%28 = OpExtInst %void %2 DebugScope %23
%32 = OpExtInst %void %2 DebugLine %4 %uint_47 %uint_47 %uint_5 %uint_6
%34 = OpExtInst %void %2 DebugLine %4 %uint_47 %uint_47 %uint_5 %uint_6
%35 = OpExtInst %void %2 DebugLine %4 %uint_47 %uint_47 %uint_5 %uint_6
%69 = OpExtInst %void %2 DebugDeclare %node %20 %68
%70 = OpExtInst %void %2 DebugLine %4 %uint_48 %uint_48 %uint_5 %uint_6
%75 = OpAccessChain %_ptr_StorageBuffer_float %outputBuffer %int_0 %int_0
%84 = OpAccessChain %_ptr_Uniform_18 %Constants %int_0
%85 = OpLoad %_ptr_PhysicalStorageBuffer_LinkedNode_natural %84
%86 = OpFunctionCall %float %test %85
OpStore %75 %86
OpReturn
OpFunctionEnd

; Function test
%test = OpFunction %float None %88
%pNode = OpFunctionParameter %_ptr_PhysicalStorageBuffer_LinkedNode_natural     ; Aliased
%90 = OpLabel
%92 = OpVariable %_ptr_Function_18 Function         ; AliasedPointer
%93 = OpVariable %_ptr_Function_18 Function         ; AliasedPointer
%99 = OpExtInst %void %2 DebugFunctionDefinition %95 %test
%100 = OpExtInst %void %2 DebugScope %95
%103 = OpExtInst %void %2 DebugDeclare %pNode_0 %92 %68
OpStore %92 %pNode
%105 = OpExtInst %void %2 DebugLine %4 %uint_35 %uint_35 %uint_5 %uint_6
%107 = OpExtInst %void %2 DebugLine %4 %uint_35 %uint_35 %uint_5 %uint_6
%108 = OpExtInst %void %2 DebugLine %4 %uint_35 %uint_35 %uint_5 %uint_6
%112 = OpExtInst %void %2 DebugDeclare %pNodeNext %93 %68
%115 = OpAccessChain %_ptr_PhysicalStorageBuffer_18 %pNode %int_2
%pNodeNext_0 = OpLoad %_ptr_PhysicalStorageBuffer_LinkedNode_natural %115 Aligned 8
OpStore %93 %pNodeNext_0
%118 = OpExtInst %void %2 DebugLine %4 %uint_36 %uint_36 %uint_5 %uint_6
%122 = OpAccessChain %_ptr_PhysicalStorageBuffer__ptr_PhysicalStorageBuffer_float %pNode %int_1
%123 = OpLoad %_ptr_PhysicalStorageBuffer_float %122 Aligned 8
%124 = OpLoad %float %123 Aligned 4
%125 = OpAccessChain %_ptr_PhysicalStorageBuffer_float %pNodeNext_0 %int_0
%126 = OpLoad %float %125 Aligned 4
%127 = OpFAdd %float %124 %126
OpReturnValue %127
OpFunctionEnd
```

### PR DESCRIPTION
**Pull request by csyonghe**
Closes #6028.

Layout decorations on ptr types of allowed storage class shouldn't be as explicit layout decorations of struct types that uses it.

### CODE REVIEW

**Review by alan-baker — CHANGES_REQUESTED** [review]
Please add a simple test (stripped down from the issue) to catch this.

**Comment by csyonghe** [comment]
@alan-baker I've added a test and verified that the test would fail without the change.

File: test/val/val_decoration_test.cpp [hunk 1]
```diff
@@ -10964,6 +10964,40 @@ OpFunctionEnd
...
+%entry = OpLabel
+%obj = OpVariable %_ptr_Function_Foo Function
+%obj_member = OpAccessChain %_ptr_Function__ptr_PhysicalStorageBuffer_int %obj %int_0
+%nullptr = OpConvertUToPtr %_ptr_PhysicalStorageBuffer_int %ulong_0
+OpStore %obj_member %nullptr
+OpReturn
+OpFunctionEnd
+)";
+
+  CompileSuccessfully(spirv, SPV_ENV_UNIVERSAL_1_4);
```
Comment (alan-baker) [inline test/val/val_decoration_test.cpp:10997]: The original change had a bug here, I think this needs to be 1.5. The Vulkan text is versions 1.4 and earlier. I had coded the inequality wrong. That fix is merged if you want to double check.

```suggestion
  CompileSuccessfully(spirv, SPV_ENV_UNIVERSAL_1_5);
```

**Review by alan-baker — CHANGES_REQUESTED** [review]
Thanks for adding the test. I think you're the victim of a separate bug I fixed in the versioning though, sorry.

**Comment by csyonghe** [comment]
Yeah, I am aware of that follow up fix, but this issue is reproducible with either 1.4 or 1.5. I am testing with your patch.

**Review by alan-baker — APPROVED** [review]

File: source/val/validate_decorations.cpp [hunk 2]
```diff
@@ -2132,14 +2132,21 @@ bool UsesExplicitLayout(ValidationState_t& vstate, uint32_t type_id,
...
-                                 d.dec_type() == spv::Decoration::MatrixStride;
-                        });
+      bool allowLayoutDecorations = false;
+      if (type_inst->opcode() == spv::Op::OpTypePointer) {
+        const auto sc = type_inst->GetOperandAs<spv::StorageClass>(1);
+        allowLayoutDecorations = AllowsLayout(vstate, sc);
+      }
+      if (!allowLayoutDecorations) {
+        res = std::any_of(
+          iter->second.begin(), iter->second.end(), [](const Decoration& d) {
```
Comment (alan-baker) [inline source/val/validate_decorations.cpp:2142]:
```suggestion
            iter->second.begin(), iter->second.end(), [](const Decoration& d) {
```
