### PR TITLE
[OPT] Fix generating debugLocalVariable from debugGlobalVariable

### LINKED ISSUE #5776: `DebugInfoManager::ConvertDebugGlobalToLocalVariable` incorrectly converts a debug global variable to a debug local variable.
## Summary

Hey all,

I believe this code in `DebugInfoManager::ConvertDebugGlobalToLocalVariable` incorrectly handles converting the operands from `DebugGlobalVariable` to `DebugLocalVariable`.

https://github.com/KhronosGroup/SPIRV-Tools/blob/edc68950bf725edc89b3e1974c533454cf2ae37c/source/opt/debug_info_manager.cpp#L775-L778

`NumInOperands` (typically returning 11) only represents the input operands count but `kDebugLocalVariableOperandFlagsIndex` is written in absolute operands (10).

Additionally, I think we want `i > kDebugLocalVariableOperandFlagsIndex` not `i >= kDebugLocalVariableOperandFlagsIndex` since we don't want to erase the flags operand.

I believe the correct code should look similar to:

```
for (uint32_t i = dbg_global_var->NumOperands() - 1; i > kDebugLocalVariableOperandFlagsIndex; --i) {
    dbg_global_var->RemoveOperand(i);
}
```

## Repro Steps

I've included an example case using Shaderplayground and DXC:

https://shader-playground.timjones.io/b7f995367a738273718f6813ec847b8e

`%37 = OpExtInst %void %1 DebugLocalVariable %14 %17 %23 %uint_6 %uint_20 %24 %uint_8 %uint_8`

Notice that `%37` represents the global `Pi` but notice the `args` operand is set to `%uint_8` even though this is a global and not the 8th argument in a function.

When we disable optimizations we see the original variable declaration before the conversion.

https://shader-playground.timjones.io/c9f52e4e48b2de44f65e185b3e800a78

`%48 = OpExtInst %void %1 DebugGlobalVariable %47 %19 %24 %uint_6 %uint_20 %25 %47 %Pi %uint_8`

## Conclusion

Hopefully this provides the information necessary. Let me know if there's anything else I can do to help.

Apologies for not directly submitting a patch. I don't have the appropriate testing environment set up.

### PR DESCRIPTION
**Pull request by s-perron**
The code converting the global to local was generating an extra operand
that was incorrect. Fixed the code, and added a unit test.

Fixes #5776

### CODE REVIEW

File: source/opt/debug_info_manager.cpp [hunk 1]
```diff
@@ -768,15 +768,29 @@ void DebugInfoManager::ConvertDebugGlobalToLocalVariable(
...
+  // Move the flags operand.
   auto flags = dbg_global_var->GetSingleWordOperand(
       kDebugGlobalVariableOperandFlagsIndex);
-  for (uint32_t i = dbg_global_var->NumInOperands() - 1;
-       i >= kDebugLocalVariableOperandFlagsIndex; --i) {
+  dbg_global_var->SetOperand(kDebugLocalVariableOperandFlagsIndex, {flags});
+
+  // Remove the  extra operands. Starting at the end to avoid copying too much
+  // data.
+  for (uint32_t i = dbg_global_var->NumOperands() - 1;
```
Comment (Keenuts) [inline source/opt/debug_info_manager.cpp:788]: nit: assert that `dbg_global_var->NumOperands()` is > 0 since this is an assumption. (previous code didn't do it, but since we are touching the loop)

File: source/opt/debug_info_manager.cpp [hunk 2]
```diff
@@ -768,15 +768,29 @@ void DebugInfoManager::ConvertDebugGlobalToLocalVariable(
          local_var->opcode() == spv::Op::OpFunctionParameter);
 
   // Convert |dbg_global_var| to DebugLocalVariable
+  // All of the operands upto the scope operand are the same for the type
```
Comment (Keenuts) [inline source/opt/debug_info_manager.cpp:771]:
```suggestion
  // All of the operands up to the scope operand are the same for the type
```

File: source/opt/debug_info_manager.cpp [hunk 3]
```diff
@@ -768,15 +768,29 @@ void DebugInfoManager::ConvertDebugGlobalToLocalVariable(
...
+  // instructions. The flag operand needs to move from operand
+  // kDebugGlobalVariableOperandFlagsIndex to
+  // kDebugLocalVariableOperandFlagsIndex. No other operands are needed for to
+  // define the DebugLocalVariable.
```
Comment (Keenuts) [inline source/opt/debug_info_manager.cpp:775]:
```suggestion
  // kDebugLocalVariableOperandFlagsIndex. No other operands are needed to
  // define the DebugLocalVariable.
```

**Review by Keenuts — APPROVED** [review]

File: source/opt/debug_info_manager.cpp (hunk 1 above)
Comment (s-perron) [reply source/opt/debug_info_manager.cpp:788]: The check for the common debug opcode guarentess that there is at least 1 operand.  These are extended instructions, so the extended instruction opcode is an operand. In fact, it is an in-operand.
