### PR TITLE
Fix reachability in the validator

### LINKED ISSUE #3529: spirv-fuzz: TransformationMoveBlockDown invalidates the module
Consider the following file.
[shader.txt](https://github.com/KhronosGroup/SPIRV-Tools/files/4919001/shader1.txt)

It contains a perfectly valid SPIR-V (i.e. the following test succeeds).
```cpp
TEST(A, a) {
  std::string shader; // code from the file

  const auto env = SPV_ENV_UNIVERSAL_1_3;
  const auto consumer = nullptr;
  const auto context = BuildModule(env, consumer, shader, kFuzzAssembleOption);
  ASSERT_TRUE(IsValid(env, context.get()));
}
```

However, if we try to move a basic block with id `370` one block down, the transformation will be applied correctly (i.e. `TransformationMoveBlockDown::IsApplicable` returns `true`) but the `spirv-val` will fail with with a somewhat ambiguous message:
```
error: line 121: Case construct that targets 310[%310] has invalid branch to block 414[%414] (not another case construct, corresponding merge, outer loop merge or outer loop continue)
  %310 = OpLabel
```

Commit id is 7afbc0c8.

### PR DESCRIPTION
**Pull request by alan-baker**
Fixes #3529

* Make BasicBlock::reachable() only consider static reachability
* Fix reachability calculation to be independent of block order
* add tests

Also tested against CTS.

### CODE REVIEW

File: source/val/function.h [hunk 1]
```diff
@@ -98,8 +98,7 @@ class Function {
   ///
   /// @param[in] successors_list A list of ids to the block's successors
   /// @param[in] branch_instruction the branch instruction that ended the block
```
Comment (dneto0) [inline source/val/function.h:100]: nit: Delete the branch_instruction comment too.
