### PR TITLE
Case validation with repeated labels

### LINKED ISSUE #2686: spirv-val fails to validate for OpSwitch case-to-case branching
```
; SPIR-V
; Version: 1.0
; Generator: Khronos Glslang Reference Front End; 7
; Bound: 35
; Schema: 0
               OpCapability Shader
          %1 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical GLSL450
               OpEntryPoint Fragment %main "main" %vIndex %vCond %FragColor
               OpExecutionMode %main OriginUpperLeft
               OpSource GLSL 450
               OpName %main "main"
               OpName %vIndex "vIndex"
               OpName %vCond "vCond"
               OpName %a "a"
               OpName %b "b"
               OpName %c "c"
               OpName %FragColor "FragColor"
               OpDecorate %vIndex Flat
               OpDecorate %vIndex Location 0
               OpDecorate %vCond Flat
               OpDecorate %vCond Location 1
               OpDecorate %FragColor Location 0
       %void = OpTypeVoid
          %3 = OpTypeFunction %void
        %int = OpTypeInt 32 1
%_ptr_Input_int = OpTypePointer Input %int
     %vIndex = OpVariable %_ptr_Input_int Input
      %vCond = OpVariable %_ptr_Input_int Input
      %int_0 = OpConstant %int 0
       %bool = OpTypeBool
%_ptr_Function_int = OpTypePointer Function %int
     %int_10 = OpConstant %int 10
    %int_100 = OpConstant %int 100
     %int_20 = OpConstant %int 20
     %int_30 = OpConstant %int 30
      %float = OpTypeFloat 32
    %v4float = OpTypeVector %float 4
%_ptr_Output_v4float = OpTypePointer Output %v4float
  %FragColor = OpVariable %_ptr_Output_v4float Output
       %main = OpFunction %void None %3
          %5 = OpLabel
          %a = OpVariable %_ptr_Function_int Function
          %b = OpVariable %_ptr_Function_int Function
          %c = OpVariable %_ptr_Function_int Function
          %9 = OpLoad %int %vIndex
               OpSelectionMerge %merge_block None
               OpSwitch %9 %12 1 %12 0 %11 2 %12
         %10 = OpLabel
         %14 = OpLoad %int %vCond
         %17 = OpINotEqual %bool %14 %int_0
               OpBranchConditional %17 %12 %merge_block
         %11 = OpLabel
               OpStore %b %int_20
               OpStore %c %int_30
               OpBranch %merge_block
         %12 = OpLabel
		 	   OpBranch %11
         %merge_block = OpLabel
               OpReturn
               OpFunctionEnd
```

This shader passes validation even if we have a construct like:

```
               OpSwitch %9 %12 1 %12 0 %11 2 %12
         %12 = OpLabel
		 	   OpBranch %11
```

The rule which seems to be violated here is:

if Target T1 branches to Target T2, or if Target T1 branches to the Default and the Default branches to Target T2, then
T1 must immediately precede T2 in the list of the OpSwitch Target operands

Is it legal to emit case label targets out of order like this?

### PR DESCRIPTION
**Pull request by alan-baker**
Fixes #2686

* Update validation to handle the default case being mentioned multiple
times
  * new tests

### CODE REVIEW

File: source/val/validate_cfg.cpp [hunk 1]
```diff
@@ -493,41 +493,54 @@ spv_result_t StructuredSwitchChecks(ValidationState_t& _, Function* function,
...
-      } else {
-        where->second++;
+      if (auto error = FindCaseFallThrough(_, target_block, &case_fall_through,
+                                           merge, case_targets, function)) {
+        return error;
       }
+
+      // Track how many time the fall through case has been targeted.
+      if (case_fall_through != 0u) {
+        auto where = num_fall_through_targeted.lower_bound(case_fall_through);
```
Comment (dneto0) [inline source/val/validate_cfg.cpp]: Driveby, previous issue with this code.

Gee, I think all this can be replaced by num_fall_through_targeted[case_fall_through]++;  

That's because accessing a missing element in a map creates the entry and zero initializes it.

No request for change here.

**Comment by dneto0** [comment]
It's been a while. Please rebase so we get an updated picture from the bots.
