### PR TITLE
spirv-fuzz: consider additional access chain instructions

### LINKED ISSUE #3671: spirv-fuzz: Invalidation when indexing into a structure
`spirv-val` invalidated a fuzzed shader because the result id of an `OpConstantNull` instruction was being used to index into a structure. According to SPIR-V specification, when indexing into a structure, each index must be the result id of an `OpConstant` instruction.
```
error: line 79: The <id> passed to OpInBoundsAccessChain to index into a structure must be an OpConstant.
  %399 = OpConstantNull %uint
```
Debugging `spirv-fuzz`, I found that `TransformationReplaceIdWithSynonym` checks only if the index instruction is `OpAccessChain`, while the same is true for `OpInBoundsAccessChain` and `OpPtrAccessChain`.

### PR DESCRIPTION
**Pull request by andreperezmaselco**
`TransformationReplaceIdWithSynonym` is careful to avoid replacing id uses that index into a struct with synonyms because the indices must only be `OpConstant` instructions. However, the check only considered `OpAccessChain` instructions, even though the same restriction applies to `OpInBoundsAccessChain`, `OpPtrAccessChain`, etc. 

This change extends the check to include all access chain instructions.

Fixes #3671.

### CODE REVIEW

File: source/opcode.cpp [hunk 1]
```diff
@@ -719,3 +719,14 @@ std::vector<uint32_t> spvOpcodeMemorySemanticsOperandIndices(SpvOp opcode) {
...
+bool spvOpcodeIsAccessChain(SpvOp opcode) {
+  switch (opcode) {
+    case SpvOpAccessChain:
+    case SpvOpInBoundsAccessChain:
+    case SpvOpPtrAccessChain:
+      return true;
+    default:
+      return false;
+  }
+}
```
Comment (Vasniktel) [inline source/opcode.cpp:732]: It might be better to make it a separate PR since it changes some code outside of the spirv-fuzz tool. I'm not sure whether this is critical, though. @paulthomson, what do you think?

**Comment by Vasniktel** [comment]
It is also good to add some tests to cover the bug.

File: source/opcode.cpp (hunk 1 above)
Comment (paulthomson) [reply source/opcode.cpp:732]: I agree. We prefer to let the spirv-opt folks approve changes in their code.

Comment (paulthomson) [reply source/opcode.cpp:732]: But it looks like a good change so I am guess they will approve.

Comment (andreperezmaselco) [reply source/opcode.cpp:732]: Done.
