### PR TITLE
Move usage detection to after all instructions are registered

### LINKED ISSUE #2373: Validator: unreachable loop with unreachable continue fails validation
The following SPIRV contains an unreachable loop with an unreachable continue target and an unreachable merge block. It fails validation:

```
error: line 17: Back-edges (11 -> 13) can only be formed between a block and a loop header.
  %11 = OpLabel
```

```asm
               OpCapability Shader
          %1 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical GLSL450
               OpEntryPoint Fragment %2 "main"
               OpExecutionMode %2 OriginUpperLeft
               OpSource ESSL 310
               OpName %2 "main"
          %3 = OpTypeVoid
          %4 = OpTypeFunction %3
          %5 = OpTypeInt 32 1
          %6 = OpTypePointer Function %5
          %7 = OpTypeBool
          %8 = OpConstantFalse %7

          %2 = OpFunction %3 None %4

          %9 = OpLabel
               OpBranch %10

         %11 = OpLabel                   ; header
               OpLoopMerge %12 %13 None
               OpBranch %14
         %13 = OpLabel                   ; continue
               OpBranch %11
         %14 = OpLabel
               OpReturn
         %12 = OpLabel                   ; merge
               OpBranch %10

         %10 = OpLabel
               OpReturn
               OpFunctionEnd
```

### PR DESCRIPTION
**Pull request by zoddicus**
This is required to properly handle uses of forward declared ids. Since forward
declared ids were not being properly covered by the validator this uncovered a
bunch of small issues that needed to be resolved to get tests passing again.

This needs to be in its own loop because some of the checks in the later loop depend on all of the usage information being calculated.

Fixes #2373

### CODE REVIEW

File: source/val/validate.cpp [hunk 1]
```diff
@@ -399,6 +398,11 @@ spv_result_t ValidateBinaryUsingContextAndValidationState(
   // Catch undefined forward references before performing further checks.
   if (auto error = ValidateForwardDecls(*vstate)) return error;
 
+  for (size_t i = 0; i < vstate->ordered_instructions().size(); ++i) {
```
Comment (alan-baker) [inline source/val/validate.cpp]: Please add a comment to explain why this is here so we're not tempted to move it later.

File: source/val/validate_decorations.cpp [hunk 2]
```diff
@@ -1185,6 +1185,9 @@ spv_result_t CheckFPRoundingModeForShaders(ValidationState_t& vstate,
   // Validates Object operand of an OpStore
   for (const auto& use : inst.uses()) {
     const auto store = use.first;
+    if (store->opcode() == SpvOpFConvert) continue;
+    if (store->opcode() == SpvOpDecorate) continue;
```
Comment (alan-baker) [inline source/val/validate_decorations.cpp]: Should probably skip spvOpcodeIsDebug too. I would also consider adding spvOpcodeIsAnnotation and skipping all those instead of just the decorate and member decorate.

File: source/val/validate_type.cpp [hunk 3]
```diff
@@ -324,10 +324,12 @@ spv_result_t ValidateTypeFunction(ValidationState_t& _,
            << num_args << " arguments.";
   }
 
-  // The only valid uses of OpTypeFunction are in an OpFunction instruction.
+  // The only valid uses of OpTypeFunction are in an OpFunction or debugging
+  // instruction.
   for (auto& pair : inst->uses()) {
     const auto* use = pair.first;
-    if (use->opcode() != SpvOpFunction) {
+    if (use->opcode() != SpvOpFunction && use->opcode() != SpvOpName &&
```
Comment (alan-baker) [inline source/val/validate_type.cpp]: Same here for skipping debug and annotations.

File: source/val/validate.cpp (hunk 1 above)
Comment (zoddicus) [reply source/val/validate.cpp]: Done

File: source/val/validate_decorations.cpp (hunk 2 above)
Comment (zoddicus) [reply source/val/validate_decorations.cpp]: Done.
FYI, there is no spvOpcodeIsAnnotation, I am assuming you meant spvOpcodeIsDecoration.

File: source/val/validate_type.cpp (hunk 3 above)
Comment (zoddicus) [reply source/val/validate_type.cpp]: Done
