### PR TITLE
Fix endianness of string literals

### LINKED ISSUE #149: Literal string endianness is handled incorrectly
The code currently assumes that strings can be directly read in and written to disk without being swapped, but this isn't true. The SPIR-V spec, in the definition of "literal string" (section 2.2.1), says that "the UTF-8 octets (8-bit bytes) are packed four per word, following the little-endian convention (i.e., the first octet is in the lowest-order 8 bits of the word)." That is, literal strings are defined in terms of *words*, just like everything else in SPIR-V. While the way that bytes on-disk get transformed to words isn't defined by the spec, it wouldn't make any sense to define it "just so" so that the way SPIR-V Tools is currently parsing the SPIR-V would be correct, and I can say that that wasn't the intent when the language in section 2.2.1 was added. That is, it's expected that when reading from byte-oriented formats, if the magic word is flipped, then the entire module is flipped. Practically, this also makes loading SPIR-V from disk in games much easier, since they don't need to know about what's a string vs. what isn't -- just check the magic word and flip the bytes if necessary.

### PR DESCRIPTION
**Pull request by mhillenbrand**
To get correct and consistent encoding and decoding of string literals
on big-endian platforms, use spvtools::utils::MakeString and MakeVector
(or wrapper functions) consistently for handling string literals.

- add variant of MakeVector that encodes a string literal into an
  existing vector of words
- add variants of MakeString
- add a wrapper spvDecodeLiteralStringOperand in source/
- fix wrapper Operand::AsString to use MakeString (source/opt)
- remove Operand::AsCString as broken and unused
- add a variant of GetOperandAs for string literals (source/val)
... and apply those wrappers throughout the code.

Extend test cases
- StringLiterals.RoundTripLiteralsTest,
- StringLiterals.RoundTripSpecialCaseLiteralsTest, and
- BinaryParseTest.InstructionWithStringOperand

to attempt decoding both with the host's own byte order and with flipped words, that is, test decoding SPIR-V binaries in both little-endian and big-endian orders. The cross-endian test cases fail without the fixes in this PR.

Fixes  #149

Tested on x86-64 and s390x, there are no regressions in the testsuite.

### CODE REVIEW

**Comment by greg-lunarg** [comment]
Let me know when this is merged and I will merge https://github.com/KhronosGroup/glslang/pull/2800

File: source/util/string_utils.h [hunk 1]
```diff
@@ -44,9 +46,9 @@ std::string CardinalToOrdinal(size_t cardinal);
 // string will be empty.
 std::pair<std::string, std::string> SplitFlagArgs(const std::string& flag);
 
-// Encodes a string as a sequence of words, using the SPIR-V encoding.
-inline std::vector<uint32_t> MakeVector(std::string input) {
-  std::vector<uint32_t> result;
+// Encodes a string as a sequence of words, using the SPIR-V encoding, appending
+// to an existing vector.
+inline void AppendToVector(std::string input, std::vector<uint32_t>& result) {
```
Comment (dneto0) [inline source/util/string_utils.h:51]: Please avoid non-const references.
This codebase has avoided them (except for I/O streams).

**Comment by mhillenbrand** [comment]
I have added two commits that extend the test cases StringLiterals.RoundTripLiteralsTest,
StringLiterals.RoundTripSpecialCaseLiteralsTest, and BinaryParseTest.InstructionWithStringOperand to test decoding from both little-endian and big-endian byte order. The tests encode into the host's own byte order as usual and then do / do not flip byte order before attempting decode, as many other test cases already do.

As expected, the "cross-endian" test cases would fail without the fixes in this patch because the decoding step would always assume the host's byte order.

I have updated this PR's description to reflect this extension.

**Comment by mhillenbrand** [comment]
Steven @s-perron, you have added encoding and decoding of string literals in source/util/string_utils.[h|cpp]. Could you please take a look at this PR extending your code?

File: source/util/string_utils.h [hunk 2]
```diff
@@ -56,23 +58,33 @@ inline std::vector<uint32_t> MakeVector(std::string input) {
...
+// assertFoundTerminatingNull is passed as false).
+template <class InputIt>
+inline std::string MakeString(InputIt first, InputIt last,
+                              bool assertFoundTerminatingNull = true) {
   std::string result;
 
-  for (uint32_t word : words) {
+  for (InputIt pos = first; pos != last; ++pos) {
+    uint32_t word = *pos;
     for (int byte_index = 0; byte_index < 4; byte_index++) {
```
Comment (s-perron) [inline source/util/string_utils.h:88]: I know you did not do this, but we should probably not be use "4" as a literal here.  We use 4 because we are assuming that "*pos" is 4 bytes.  We should provide a named constant for this, and add a static assert.

File: source/util/string_utils.h [hunk 3]
```diff
@@ -56,23 +58,33 @@ inline std::vector<uint32_t> MakeVector(std::string input) {
...
 
-// Decode a string from a sequence of words, using the SPIR-V encoding.
-template <class VectorType>
-inline std::string MakeString(const VectorType& words) {
+// Decode a string from a sequence of words between first and last, using the
+// SPIR-V encoding. Assert that a terminating 0-byte was found (unless
+// assertFoundTerminatingNull is passed as false).
+template <class InputIt>
+inline std::string MakeString(InputIt first, InputIt last,
+                              bool assertFoundTerminatingNull = true) {
```
Comment (s-perron) [inline source/util/string_utils.h:83]: We follow the Google style guide (https://google.github.io/styleguide/cppguide.html#Variable_Names).  The variable name should be `assert_fount_terminating_null`.  I know not everything follows it.  Some code predates us using that style.  New code should try to fix it up.

**Review by s-perron — CHANGES_REQUESTED** [review]
LGTM.  There is just a few variable names that need to be changed to have the correct format. Sorry I did not spot this PR earlier.

File: source/util/string_utils.h (hunk 2 above)
Comment (mhillenbrand) [reply source/util/string_utils.h]: Agreed, good catch.

**Comment by s-perron** [comment]
@mhillenbrand The CI runs use the latest from all of the dependencies, so you will need to rebase on top of the latest master to get the tests to pass.

**Comment by mhillenbrand** [comment]
@s-perron Thanks for starting the test runs. I have rebased and checked the build + local testsuite with updated dependencies (git-sync-deps)

**Comment by s-perron** [comment]
Look like there might be a memory leak somewhere.  The asan build it failing.  Can you look into that.  If you cannot see anything or you do not believe it is related to your change, then let me know and I will look into it.

**Comment by mhillenbrand** [comment]
I will take a look today. I cannot access the logs of the failing CI run (the link "Details" leads nowhere) yet I should be able to reproduce that locally with the scripts in kokoro/.

**Comment by s-perron** [comment]
I just noticed another PR failed the asan build in same way.  I'll double check it, but I might merge this anyway.

**Comment by mhillenbrand** [comment]
Thanks for merging!

I reproduced the ASAN runs as close to the CI as I could -- using `./kokoro/linux-clang-asan/build.sh` and slightly adjusting `./kokoro/scripts/linux/build.sh` -- yet the test run completed successfully. fwiw, in an early run LeakSanitizer bailed out because I was missing options to docker (`--cap-add SYS_PTRACE`).
