### PR TITLE
spirv-val: Fix ubsan error

### LINKED ISSUE #4504: Ubsan error in spirv-val
OSS-Fuzz has found a Ubsan error in spirv-val. The [OSS-Fuzz report](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=37821) has limited visibility, so this is a mirroring issue.

The problem is that spirv-val does this in a couple of places:

```
SpvOp(word)
```

where `word` might not be in the range of values associated with the `SpvOp` type.

The `SpvOp` type is declared like this:

```
typedef enum SpvOp_ {
  SpvOpNop = 0,
  SpvOpUndef = 1,
  ...
  SpvOpConstantCompositeContinuedINTEL = 6091,
  SpvOpSpecConstantCompositeContinuedINTEL = 6092,
  SpvOpMax = 0x7fffffff,
} SpvOp;
```

Two ways to fix the issue are:

1. Specify 32-bit integer as the underlying type of SpvOp, like so:

```
typedef enum SpvOp_ uint32_t {
  SpvOpNop = 0,
  SpvOpUndef = 1,
  ...
  SpvOpConstantCompositeContinuedINTEL = 6091,
  SpvOpSpecConstantCompositeContinuedINTEL = 6092,
  SpvOpMax = 0x7fffffff,
} SpvOp;
```

2. Change the definition of SpvOpMax to `0xffffffff` (or add another enumeration constant with that value).

I assume there is some reason why `SpvOpMax` is declared as `0x7ffffff` (largest positive signed 32-bit integer). So it would seem inadvisable to change this.

Changing the underlying type to uint32_t would seem best, though spirv.h, part of SPIR-V Headers, does not include <inttypes.h>, so it would either need to include this file, or "unsigned int" should be used in place of "uint32_t" (but that wouldn't be portable to platforms where the size of unsigned int is not 32-bit).

### PR DESCRIPTION
**Pull request by afd**
Fixes an issue where an arbitrary word was cast to SpvOp, leading to
undefined behaviour if the value of the word fell outside the range of
SpvOp values.

Fixes #4504.

### CODE REVIEW

**Review by s-perron — APPROVED** [review]

File: source/binary.cpp [hunk 1]
```diff
@@ -507,7 +507,8 @@ spv_result_t Parser::parseOperand(size_t inst_offset,
 
     case SPV_OPERAND_TYPE_SPEC_CONSTANT_OP_NUMBER: {
       assert(SpvOpSpecConstantOp == opcode);
-      if (grammar_.lookupSpecConstantOpcode(SpvOp(word))) {
+      if (word > static_cast<uint32_t>(SpvOp::SpvOpMax) ||
+          grammar_.lookupSpecConstantOpcode(SpvOp(word))) {
```
Comment (dneto0) [inline source/binary.cpp:511]: If this was widespread, I would advocate adding an overload that took uint32_t, and did the check in the overload.  But this is fine for me.
