### PR TITLE
Fix merge blocks opportunity to check if still enabled

### LINKED ISSUE #2369: reducer: merge_blocks pass fails to check for invalidation of merge block opportunity
`MergeBlocksReductionOpportunity` assumes it can never be invalidated/disabled by another `MergeBlocksReductionOpportunity` being applied, but this is not true. A loop header and a return block cannot be merged, and the return block might not start out as a return block; it can become a return block due to another merge.

### PR DESCRIPTION
**Pull request by paulthomson**
Fixes #2369. Added tests.

### CODE REVIEW

File: source/reduce/merge_blocks_reduction_opportunity.cpp [hunk 1]
```diff
@@ -34,9 +34,13 @@ MergeBlocksReductionOpportunity::MergeBlocksReductionOpportunity(
 }
 
 bool MergeBlocksReductionOpportunity::PreconditionHolds() {
-  // By construction, it is not possible for the merging of A->B to disable the
-  // merging of C->D, even when B and C are the same block.
-  return true;
```
Comment (afd) [inline source/reduce/merge_blocks_reduction_opportunity.cpp]: It would be good to have a comment explaining that there do exist scenarios where one merge can disable another merge.  Giving one example would help.

File: test/reduce/merge_blocks_test.cpp [hunk 2]
```diff
@@ -508,6 +508,144 @@ TEST(MergeBlocksReductionPassTest, MergeWithOpPhi) {
   CheckEqual(env, after, context.get());
 }
 
+void MergeBlocksReductionPassTest_LoopReturn_Helper(bool reverse) {
```
Comment (afd) [inline test/reduce/merge_blocks_test.cpp]: Great that we have this example in the tests.  Still, a comment in the precondition checking code would be good.

File: source/reduce/merge_blocks_reduction_opportunity.cpp (hunk 1 above)
Comment (paulthomson) [reply source/reduce/merge_blocks_reduction_opportunity.cpp]: Sounds good. Done.
