### PR TITLE
spirv-val: Make it legal to use arrays of ray queries

### LINKED ISSUE #4917: Validator: False positive in OpRayQueryInitialize
This SPIR-V triggers a weird validator error. The shader is from SPIRV-Cross test suite.

```
; SPIR-V
; Version: 1.6
; Generator: Khronos Glslang Reference Front End; 10
; Bound: 120
; Schema: 0
               OpCapability Shader
               OpCapability RayQueryKHR
               OpCapability RayTraversalPrimitiveCullingKHR
               OpExtension "SPV_KHR_ray_query"
          %1 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical GLSL450
               OpEntryPoint GLCompute %4 "main" %10 %13 %20 %46
               OpExecutionModeId %4 LocalSizeId %7 %7 %7
               OpSource GLSL 460
               OpSourceExtension "GL_EXT_ray_flags_primitive_culling"
               OpSourceExtension "GL_EXT_ray_query"
               OpSourceExtension "GL_EXT_ray_tracing"
               OpName %4 "main"
               OpName %10 "q"
               OpName %13 "AS"
               OpName %18 "Params"
               OpMemberName %18 0 "ray_flags"
               OpMemberName %18 1 "cull_mask"
               OpMemberName %18 2 "origin"
               OpMemberName %18 3 "tmin"
               OpMemberName %18 4 "dir"
               OpMemberName %18 5 "tmax"
               OpMemberName %18 6 "thit"
               OpMemberName %18 7 "bda"
               OpName %20 ""
               OpName %46 "q2"
               OpName %67 "res"
               OpName %75 "fval"
               OpName %78 "type"
               OpName %82 "fvals"
               OpName %94 "ival"
               OpName %116 "matrices"
               OpDecorate %13 DescriptorSet 0
               OpDecorate %13 Binding 0
               OpMemberDecorate %18 0 Offset 0
               OpMemberDecorate %18 1 Offset 4
               OpMemberDecorate %18 2 Offset 16
               OpMemberDecorate %18 3 Offset 28
               OpMemberDecorate %18 4 Offset 32
               OpMemberDecorate %18 5 Offset 44
               OpMemberDecorate %18 6 Offset 48
               OpMemberDecorate %18 7 Offset 56
               OpDecorate %18 Block
               OpDecorate %20 DescriptorSet 0
               OpDecorate %20 Binding 1
          %2 = OpTypeVoid
          %3 = OpTypeFunction %2
          %6 = OpTypeInt 32 0
          %7 = OpConstant %6 1
          %8 = OpTypeRayQueryKHR
          %9 = OpTypePointer Private %8
         %10 = OpVariable %9 Private
         %11 = OpTypeAccelerationStructureKHR
         %12 = OpTypePointer UniformConstant %11
         %13 = OpVariable %12 UniformConstant
         %15 = OpTypeFloat 32
         %16 = OpTypeVector %15 3
         %17 = OpTypeVector %6 2
         %18 = OpTypeStruct %6 %6 %16 %15 %16 %15 %15 %17
         %19 = OpTypePointer Uniform %18
         %20 = OpVariable %19 Uniform
         %21 = OpTypeInt 32 1
         %22 = OpConstant %21 0
         %23 = OpTypePointer Uniform %6
         %26 = OpConstant %21 1
         %29 = OpConstant %21 2
         %30 = OpTypePointer Uniform %16
         %33 = OpConstant %21 3
         %34 = OpTypePointer Uniform %15
         %37 = OpConstant %21 4
         %40 = OpConstant %21 5
         %43 = OpConstant %6 2
         %44 = OpTypeArray %8 %43
         %45 = OpTypePointer Private %44
         %46 = OpVariable %45 Private
         %48 = OpConstant %21 7
         %49 = OpTypePointer Uniform %17
         %65 = OpTypeBool
         %66 = OpTypePointer Function %65
         %70 = OpConstant %21 6
         %74 = OpTypePointer Function %15
         %77 = OpTypePointer Function %6
         %81 = OpTypePointer Function %16
         %86 = OpConstantTrue %65
         %91 = OpConstantFalse %65
         %93 = OpTypePointer Function %21
        %103 = OpTypeVector %15 2
        %105 = OpConstant %6 0
        %114 = OpTypeMatrix %16 4
        %115 = OpTypePointer Function %114
          %4 = OpFunction %2 None %3
          %5 = OpLabel
         %67 = OpVariable %66 Function
         %75 = OpVariable %74 Function
         %78 = OpVariable %77 Function
         %82 = OpVariable %81 Function
         %94 = OpVariable %93 Function
        %116 = OpVariable %115 Function
         %14 = OpLoad %11 %13
         %24 = OpAccessChain %23 %20 %22
         %25 = OpLoad %6 %24
         %27 = OpAccessChain %23 %20 %26
         %28 = OpLoad %6 %27
         %31 = OpAccessChain %30 %20 %29
         %32 = OpLoad %16 %31
         %35 = OpAccessChain %34 %20 %33
         %36 = OpLoad %15 %35
         %38 = OpAccessChain %30 %20 %37
         %39 = OpLoad %16 %38
         %41 = OpAccessChain %34 %20 %40
         %42 = OpLoad %15 %41
               OpRayQueryInitializeKHR %10 %14 %25 %28 %32 %36 %39 %42
         %47 = OpAccessChain %9 %46 %26
         %50 = OpAccessChain %49 %20 %48
         %51 = OpLoad %17 %50
         %52 = OpConvertUToAccelerationStructureKHR %11 %51
         %53 = OpAccessChain %23 %20 %22
         %54 = OpLoad %6 %53
         %55 = OpAccessChain %23 %20 %26
         %56 = OpLoad %6 %55
         %57 = OpAccessChain %30 %20 %29
         %58 = OpLoad %16 %57
         %59 = OpAccessChain %34 %20 %33
         %60 = OpLoad %15 %59
         %61 = OpAccessChain %30 %20 %37
         %62 = OpLoad %16 %61
         %63 = OpAccessChain %34 %20 %40
         %64 = OpLoad %15 %63
               OpRayQueryInitializeKHR %47 %52 %54 %56 %58 %60 %62 %64
         %68 = OpRayQueryProceedKHR %65 %10
               OpStore %67 %68
         %69 = OpAccessChain %9 %46 %22
               OpRayQueryTerminateKHR %69
         %71 = OpAccessChain %34 %20 %70
         %72 = OpLoad %15 %71
               OpRayQueryGenerateIntersectionKHR %10 %72
         %73 = OpAccessChain %9 %46 %26
               OpRayQueryConfirmIntersectionKHR %73
         %76 = OpRayQueryGetRayTMinKHR %15 %10
               OpStore %75 %76
         %79 = OpAccessChain %9 %46 %22
         %80 = OpRayQueryGetRayFlagsKHR %6 %79
               OpStore %78 %80
         %83 = OpRayQueryGetWorldRayDirectionKHR %16 %10
               OpStore %82 %83
         %84 = OpRayQueryGetWorldRayOriginKHR %16 %10
               OpStore %82 %84
         %85 = OpAccessChain %9 %46 %26
         %87 = OpRayQueryGetIntersectionTypeKHR %6 %85 %26
               OpStore %78 %87
         %88 = OpAccessChain %9 %46 %26
         %89 = OpRayQueryGetIntersectionCandidateAABBOpaqueKHR %65 %88
               OpStore %67 %89
         %90 = OpAccessChain %9 %46 %26
         %92 = OpRayQueryGetIntersectionTKHR %15 %90 %22
               OpStore %75 %92
         %95 = OpRayQueryGetIntersectionInstanceCustomIndexKHR %21 %10 %26
               OpStore %94 %95
         %96 = OpAccessChain %9 %46 %22
         %97 = OpRayQueryGetIntersectionInstanceIdKHR %21 %96 %22
               OpStore %94 %97
         %98 = OpRayQueryGetIntersectionInstanceShaderBindingTableRecordOffsetKHR %6 %10 %26
               OpStore %78 %98
         %99 = OpAccessChain %9 %46 %26
        %100 = OpRayQueryGetIntersectionGeometryIndexKHR %21 %99 %22
               OpStore %94 %100
        %101 = OpRayQueryGetIntersectionPrimitiveIndexKHR %21 %10 %26
               OpStore %94 %101
        %102 = OpAccessChain %9 %46 %22
        %104 = OpRayQueryGetIntersectionBarycentricsKHR %103 %102 %22
        %106 = OpAccessChain %74 %82 %105
        %107 = OpCompositeExtract %15 %104 0
               OpStore %106 %107
        %108 = OpAccessChain %74 %82 %7
        %109 = OpCompositeExtract %15 %104 1
               OpStore %108 %109
        %110 = OpRayQueryGetIntersectionFrontFaceKHR %65 %10 %26
               OpStore %67 %110
        %111 = OpRayQueryGetIntersectionObjectRayDirectionKHR %16 %10 %22
               OpStore %82 %111
        %112 = OpAccessChain %9 %46 %22
        %113 = OpRayQueryGetIntersectionObjectRayOriginKHR %16 %112 %26
               OpStore %82 %113
        %117 = OpRayQueryGetIntersectionObjectToWorldKHR %114 %10 %22
               OpStore %116 %117
        %118 = OpAccessChain %9 %46 %26
        %119 = OpRayQueryGetIntersectionWorldToObjectKHR %114 %118 %26
               OpStore %116 %119
               OpReturn
               OpFunctionEnd
```

reports in validator:

```
error: line 129: Ray Query must be a memory object declaration
  OpRayQueryInitializeKHR %47 %52 %54 %56 %58 %60 %62 %64
```

The shader is using an array of ray query objects, so the pattern is OpVariable -> OpAccessChain -> RayQueryInitialize.
This used to validate fine in 4c456f7da67c5437a6fb7d4d20d78e2a5ae2acf2. I can't find any spec text saying this is not allowed.

### PR DESCRIPTION
**Pull request by rg3igalia**
Private arrays of ray queries are legal to use. Several CTS tests check they work properly but were being rejected by spirv-val.

Fixes #4917.

### CODE REVIEW

File: source/val/validate_ray_query.cpp [hunk 1]
```diff
@@ -28,8 +28,10 @@ spv_result_t ValidateRayQueryPointer(ValidationState_t& _,
                                      uint32_t ray_query_index) {
   const uint32_t ray_query_id = inst->GetOperandAs<uint32_t>(ray_query_index);
   auto variable = _.FindDef(ray_query_id);
-  if (!variable || (variable->opcode() != SpvOpVariable &&
-                    variable->opcode() != SpvOpFunctionParameter)) {
+  const auto var_opcode = variable->opcode();
+  if (!variable || (var_opcode != SpvOpVariable &&
```
Comment (alan-baker) [inline source/val/validate_ray_query.cpp:32]: Please add a test to cover this case.

**Review by alan-baker — CHANGES_REQUESTED** [review]

File: source/val/validate_ray_query.cpp (hunk 1 above)
Comment (rg3igalia) [reply source/val/validate_ray_query.cpp:32]: This should be solved in the latest push. Let me know if that works.

**Review by alan-baker — APPROVED** [review]

**Comment by alan-baker** [comment]
Please fix the formatting errors.
