### PR TITLE
Fix layout validation

### LINKED ISSUE #5010: Push constant nested struct alignment/padding issue
We have the following set of structures that we are using for push constants:

struct StructA
{
    uint64_t   valA;  // this is technically a reference to a buffer in our shader but I don't think that matters for this discussion
    uint          valB;
    uint          valC;
    uint          valD;
};

struct StructB
{
    StructA     aValues;
    uint           valE;
    uint           valF;
};

I think that struct A will have an alignment of 8 bytes and size of 24.  The Vulkan spec points to section 7.6.22 "Standard Uniform Block Layout" of the OpenGL specification which says:

"If the member is a structure, the base alignment of the structure is N, where N is the largest base alignment value of any of its members, and rounded up to the base alignment of a vec4. The individual members of this substructure are then assigned offsets by 
 applying this set of rules recursively, where the base offset of the first member of the sub-structure is equal to the aligned offset of the structure. The structure may have padding at the end; the base offset of the member following the sub-structure is rounded up to
the next multiple of the base alignment of the structure."

By those rules the base offset of the member following the sub structure (valE) is rounded up to the next multiple of the base alignment of the structure (8).  However, spirv-dis shows that the offset of valE in this scenario is 20 when I believe it should be 24.

This is easy to work-around by inserting explicit padding or making valD a uint64_t so not a show-stopper but it did take some time to diagnose and seems like an error WRT the spec.

### PR DESCRIPTION
**Pull request by alan-baker**
Fixes #5010

* Unless scalar block layout is enabled, no member can reside at an offset between the end of the previous member that is a struct or array and the next multiple of that alignment
* Tested against Vulkan CTS

### CODE REVIEW

File: source/val/validate_decorations.cpp [hunk 1]
```diff
@@ -547,6 +547,8 @@ spv_result_t checkLayout(uint32_t struct_id, const char* storage_class_str,
           hasImproperStraddle(id, offset, constraint, constraints, vstate))
         return fail(memberIdx)
                << "is an improperly straddling vector at offset " << offset;
+      if (ordered_member_idx > 0) {
```
Comment (dneto0) [inline source/val/validate_decorations.cpp:550]: This does nothing.
Please remove.

File: source/val/validate_decorations.cpp [hunk 2]
```diff
@@ -633,10 +635,10 @@ spv_result_t checkLayout(uint32_t struct_id, const char* storage_class_str,
       }
     }
     nextValidOffset = offset + size;
-    if (!scalar_block_layout && blockRules &&
+    if (!scalar_block_layout &&
         (spv::Op::OpTypeArray == opcode || spv::Op::OpTypeStruct == opcode)) {
-      // Uniform block rules don't permit anything in the padding of a struct
-      // or array.
+      // Non-scalar block layout rules don't permit anything in the padding of
```
Comment (dneto0) [inline source/val/validate_decorations.cpp:640]: Yep, that's what the spec says.

**Review by dneto0 — APPROVED** [review]

**Review by dneto0 — APPROVED** [review]

**Comment by dneto0** [comment]
CI-windows-msvc-2015-release-bazel has been failing consistently for unrelated reasons.  #5022
