### PR TITLE
[OPT] Process debug scope instructions of debug value instructions

### LINKED ISSUE #6508: [spirv-opt] eliminate-dead-code-aggressive removes IDs still referenced by DebugScope instructions
With the latest Spirv-Tools, multiple slang tests are failing with the crash in the eliminate-dead-code-aggressive spirv-opt pass.
To reproduce this, I have attached the dummped spirv and the equivalent cfg used by Slang to invoke spirv-opt

[ioSpirv_dump.txt](https://github.com/user-attachments/files/24782336/ioSpirv_dump.txt)
[slang-spirv-opt-cfg.txt](https://github.com/user-attachments/files/24782352/slang-spirv-opt-cfg.txt)

`spirv-opt.exe -Oconfig=slang-spirv-opt-cfg.txt ./ioSpirv_dump.txt -o output.spv`

spirv-opt crashes with the following call stack
```
spirv-opt.exe!spvtools::opt::Instruction::unique_id() Line 251
	at C:\nv\slang\external\spirv-tools\source\opt\instruction.h(251)
spirv-opt.exe!spvtools::opt::AggressiveDCEPass::AddToWorklist(spvtools::opt::Instruction * inst) Line 95
	at C:\nv\slang\external\spirv-tools\source\opt\aggressive_dead_code_elim_pass.h(95)
spirv-opt.exe!spvtools::opt::AggressiveDCEPass::AddDebugScopeToWorkList(const spvtools::opt::Instruction * inst) Line 472
	at C:\nv\slang\external\spirv-tools\source\opt\aggressive_dead_code_elim_pass.cpp(472)
spirv-opt.exe!spvtools::opt::AggressiveDCEPass::AddDebugInstructionsToWorkList(const spvtools::opt::Instruction * inst) Line 490
	at C:\nv\slang\external\spirv-tools\source\opt\aggressive_dead_code_elim_pass.cpp(490)
spirv-opt.exe!spvtools::opt::AggressiveDCEPass::ProcessWorkList(spvtools::opt::Function * func) Line 460
	at C:\nv\slang\external\spirv-tools\source\opt\aggressive_dead_code_elim_pass.cpp(460)
spirv-opt.exe!spvtools::opt::AggressiveDCEPass::AggressiveDCE(spvtools::opt::Function * func) Line 286
	at C:\nv\slang\external\spirv-tools\source\opt\aggressive_dead_code_elim_pass.cpp(286)
```

Adding a nullptr check to `source\opt\aggressive_dead_code_elim_pass.cpp:472` before calling `AddToWorklist` WAR this crash, but might not be the optimal solution.

The attached `ioSpirv_dump.txt` is a spirv binary (named to txt to be able to upload) and it passes spirv-val.

### PR DESCRIPTION
**Pull request by s-perron**
When we create a debug value from a debug scope instruction in ADCE, we
add the new instruction directly to the live set. This by passes the
code that processes the operands of the new instructions to make sure
they are all live.

We do the same thing when a debug value is modify to have an undef. In
that case we have bespoke code to process some of this accociated code,
but it misses the debug scope. I replace the bespoke processing by
adding it to the worklist.

Fixes #6508

### CODE REVIEW

**Comment by s-perron** [comment]
@SteveUrquhart FYI

File: test/opt/aggressive_dead_code_elim_test.cpp [hunk 1]
```diff
@@ -8803,69 +8803,148 @@ TEST_F(AggressiveDCETest, UndefIsOutsideFunction) {
...
+  const std::string spirv = R"(
+; CHECK: [[ext:%\w+]] = OpExtInstImport "NonSemantic.Shader.DebugInfo.100"
+; CHECK-DAG: [[inlined:%\w+]] = OpExtInst %void [[ext]] DebugInlinedAt
+; CHECK-DAG: [[UniformVar:%\w+]] = OpVariable %_ptr_Uniform_float Uniform
+; CHECK: [[scope:%\w+]] = OpExtInst %void [[ext]] DebugScope {{%\w+}} [[inlined]]
+; CHECK-NEXT: OpExtInst %void [[ext]] DebugValue {{%\w+}} {{%\w+}} {{%\w+}}
+; CHECK-NEXT: DebugScope
+; CHECK-NEXT: DebugLine
+; CHECK-NEXT: OpStore [[UniformVar]] %float_0
+; CHECK-NEXT: OpReturn
```
Comment (s-perron) [inline test/opt/aggressive_dead_code_elim_test.cpp:8880]: @SteveUrquhart Note that this test shows that the OpStore will still be removed even if we add the debug value to the work list.

**Review by Keenuts — APPROVED** [review]
