### PR TITLE
Fix extract with out-of-bounds index

### LINKED ISSUE #4514: OSS-Fuzz: Null-dereference READ in spvtools::opt::FoldExtractWithConstants
OSS-Fuzz issue: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=38100&q=spvtools_opt_performance_fuzzer%20-label%3ASPIRV-Tools-Tracked&can=2

@s-perron

### PR DESCRIPTION
**Pull request by s-perron**
When folding a OpCompositeExtract that is fed by an
OpCompositeConstruct, we handle and out of bounds
index, but only in the case where the result of the
OpCompostiteConstruct is a struct.  This change
refactors that folding rule and then improves it to
handle an out-of-bounds access when the result of the
OpCompositeConstruct is a vector.

Fixes #4514

### CODE REVIEW

File: source/opt/folding_rules.cpp [hunk 1]
```diff
@@ -1463,90 +1464,115 @@ FoldingRule IntMultipleBy1() {
...
+  analysis::Vector* type = type_mgr->GetType(def->type_id())->AsVector();
+  if (type == nullptr) {
+    return 1;
+  }
+  return type->element_count();
+}
 
-    uint32_t cid = inst->GetSingleWordInOperand(kExtractCompositeIdInIdx);
-    Instruction* cinst = def_use_mgr->GetDef(cid);
+// Returns the id and the literal index into the id from which the value of the
```
Comment (jaebaek) [inline source/opt/folding_rules.cpp:1497]: By reading this description, it is a little bit difficult to know why the return type must be a vector and what is the meaning of `the id and the literal index into the id`.

It would be nice if the description explicitly mentioned that |inst| with a vector type returns `std::vector<Operand>` with **two elements** and it returns `std::vector<Operand>` with a single element for other cases.

File: source/opt/folding_rules.cpp [hunk 2]
```diff
@@ -1463,90 +1464,115 @@ FoldingRule IntMultipleBy1() {
...
-      operands.push_back({SPV_OPERAND_TYPE_ID, {element_id}});
-
-      // Add the remaining indices for extraction.
-      for (uint32_t i = 2; i < inst->NumInOperands(); ++i) {
-        operands.push_back({SPV_OPERAND_TYPE_LITERAL_INTEGER,
-                            {inst->GetSingleWordInOperand(i)}});
-      }
+  // If the result type is a vector, then vector operands are concatenated.
+  for (uint32_t idx = 0; idx < inst->NumInOperands(); ++idx) {
+    uint32_t element_count = GetOperandElementCount(context, inst, idx);
```
Comment (jaebaek) [inline source/opt/folding_rules.cpp:1515]: Before reading the line below `result_index -= element_count;`, it can be confusing. For example, someone can guess `GetOperandElementCount(..)` returns the count of all elements **until** `idx`.

A single line of comment here would be helpful e.g., `// Note that instead of accumulating the element count, we decrease |result_index| by |element_count| at the end of this loop`.

**Review by jaebaek — APPROVED** [review]
LGTM with nits.

File: source/opt/folding_rules.cpp [hunk 3]
```diff
@@ -1463,90 +1464,115 @@ FoldingRule IntMultipleBy1() {
...
+    return 1;
+  }
+  return type->element_count();
+}
 
-    uint32_t cid = inst->GetSingleWordInOperand(kExtractCompositeIdInIdx);
-    Instruction* cinst = def_use_mgr->GetDef(cid);
+// Returns the id and the literal index into the id from which the value of the
+// |result_index|th element in the result of |inst| gets its value.  Returns
+// the empty vector is no id can be found.  |inst| must be an
```
[the remark this answers is not in the document]
Comment (s-perron) [reply source/opt/folding_rules.cpp]: Done

File: source/opt/folding_rules.cpp [hunk 4]
```diff
@@ -1463,90 +1464,115 @@ FoldingRule IntMultipleBy1() {
...
+    return 1;
+  }
 
-    // If there are no index operands, then this rule cannot do anything.
-    if (inst->NumInOperands() <= 1) {
-      return false;
-    }
+  // If the result type is a vector then the operands are either scalars or
+  // vectors. If it is a scalar, then it corresponds to a single element.  If it
+  // is a vector, then each element in the vector will be and element in the
```
[the remark this answers is not in the document]
Comment (s-perron) [reply source/opt/folding_rules.cpp]: done

File: source/opt/folding_rules.cpp (hunk 1 above)
Comment (s-perron) [reply source/opt/folding_rules.cpp]: Yes, this is a very particular function.  I never got to a description and name that I was happy with.  I've changed it.  Let me know if this is better.

File: source/opt/folding_rules.cpp (hunk 2 above)
Comment (s-perron) [reply source/opt/folding_rules.cpp]: I don't like the idea of adding comment because the function name is not clear enough.  I've changed the name of the function.  I hope this is clearer.  I've also modified the loop to keep track of the number of element see so far.

**Comment by s-perron** [comment]
The clang format error is not related to my change.

File: source/opt/folding_rules.cpp (hunk 1 above)
Comment (jaebaek) [reply source/opt/folding_rules.cpp]: It is better. It is fine to submit it.

Just consider it explains how it should be used specifically for `OpConstantExtract` not the function itself. One solution would be:
1. break it up in two parts i.e., vector and non-vector types
2. add a if-statement in the caller to determine if it is a vector type or not
3. call the two split functions for each case

Benefit: the description of each function would be more clear.

**Comment by jaebaek** [comment]
I think the code format error was fixed: https://github.com/KhronosGroup/SPIRV-Tools/blob/master/include/spirv-tools/optimizer.hpp#L32

Just rebasing it would make it working.
