### PR TITLE
Have scalar replacement use undef instead of null

### LINKED ISSUE #3996: spirv-opt: Scalar replacement causes 'OpConstantNull cannot have null value' error
The following shader
```
               OpCapability Shader
          %1 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical GLSL450
               OpEntryPoint Fragment %4 "main"
               OpExecutionMode %4 OriginUpperLeft
          %2 = OpTypeVoid
          %3 = OpTypeFunction %2
         %10 = OpTypeFloat 32
         %23 = OpTypeImage %10 2D 0 0 0 1 Unknown
         %24 = OpTypeSampledImage %23
        %207 = OpTypeStruct %24
        %206 = OpTypeFunction %207
        %208 = OpUndef %207
          %4 = OpFunction %2 None %3
          %5 = OpLabel
        %203 = OpFunctionCall %207 %205
               OpReturn
               OpFunctionEnd
        %205 = OpFunction %207 None %206
        %204 = OpLabel
               OpReturnValue %208
               OpFunctionEnd
``` 
causes an error
```
error: line 15: OpConstantNull Result Type <id> '24[%24]' cannot have a null value.
  %218 = OpConstantNull %24

error: line 0: Validation failed after pass scalar-replacement=100
``` 
when executed with
```
spirv-opt --validate-after-all --inline-entry-points-exhaustive --scalar-replacement=100 <shader> -o out.spv
```
Can be reproduced on 34ae8a47.

The following archive contains assemblies for the variant shader and the reduced shader (shown above).

[data.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/5446995/data.zip)

### PR DESCRIPTION
**Pull request by s-perron**
Scalar replacement generates a null when there value for a member will
not be used.  The null is used to make sure things are
deterministic in case there is an error.

However, some type cannot be null, so we will change that to use undef.
To keep the code simpler we will always use the undef.

Fixes #3996

### CODE REVIEW

File: source/opt/scalar_replacement_pass.cpp [hunk 1]
```diff
@@ -429,6 +430,10 @@ bool ScalarReplacementPass::CreateReplacementVariables(
          replacements->end();
 }
 
+Instruction* ScalarReplacementPass::getNullOrUndef(uint32_t type_id) {
+  return get_def_use_mgr()->GetDef(Type2Undef(type_id));
```
Comment (jaebaek) [inline source/opt/scalar_replacement_pass.cpp:434]: `Type2Undef(..)` seems to always return an `OpUndef` instruction. I think this method name can be confusing. Could you please change it to `Instruction* ScalarReplacementPass::getUndef(uint32_t type_id)`?

Comment (s-perron) [reply source/opt/scalar_replacement_pass.cpp:434]: Good catch.  I did a different (and more complicated) solution at first.  I then simplified it to just returning the undef, but forgot to fix the function name and comments.  I fixed it up.
