### PR TITLE
Fix pairing of function parameters.

### LINKED ISSUE #5218: spirv-diff reports spurious differences in `OpFunctionParameter` instructions
`spirv-diff` seems to sometimes draw a distinction between `OpFunctionParameter` instructions that seem equivalent to me, resulting in spurious differences.

For example, given the two attached files, running

    $ spirv-diff before.spvasm after.spvasm

produces output that begins as follows:

```diff
                OpCapability Shader
           %1 = OpExtInstImport "GLSL.std.450"
                OpMemoryModel Logical GLSL450
                OpEntryPoint GLCompute %48 "main"
                OpExecutionMode %48 LocalSize 1 1 1
           %2 = OpTypeVoid
           %4 = OpTypeBool
           %3 = OpConstantTrue %4
           %7 = OpTypeFunction %2
          %14 = OpTypePointer Function %4
          %15 = OpConstantNull %4
          %17 = OpConstantNull %4
          %21 = OpTypeFunction %2 %4
          %32 = OpConstantNull %4
          %34 = OpConstantNull %4
           %6 = OpFunction %2 None %7
           %5 = OpLabel
                OpBranch %8
           %8 = OpLabel
                OpBranch %9
           %9 = OpLabel
                OpLoopMerge %10 %12 None
                OpBranch %11
          %11 = OpLabel
                OpBranch %12
          %12 = OpLabel
                OpBranchConditional %3 %10 %9
          %10 = OpLabel
                OpReturn
                OpFunctionEnd
          %20 = OpFunction %2 None %21
-         %19 = OpFunctionParameter %4
+         %50 = OpFunctionParameter %4
          %18 = OpLabel
          %13 = OpVariable %14 Function %15
          %16 = OpVariable %14 Function %17
                OpBranch %22
          %22 = OpLabel
                OpBranch %23
          %23 = OpLabel
                OpLoopMerge %24 %26 None
                OpBranch %25
          %25 = OpLabel
                OpBranch %26
          %26 = OpLabel
-               OpStore %13 %19
+               OpStore %13 %50
          %27 = OpLoad %4 %13
-         %28 = OpLogicalNotEqual %4 %19 %27
+         %28 = OpLogicalNotEqual %4 %50 %27
                OpStore %16 %28
          %29 = OpLoad %4 %16
-         %30 = OpLogicalEqual %4 %19 %29
+         %30 = OpLogicalEqual %4 %50 %29
                OpBranchConditional %30 %24 %23
          %24 = OpLabel
                OpReturn
                OpFunctionEnd
```

It seems to me that `%19` and `%50` are identical.

[spirv-diff-spurious.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/11448227/spirv-diff-spurious.zip)

### PR DESCRIPTION
**Pull request by jimblandy**
- Consider prior type pairings when attempting to pair function parameters by type.
- Pair all parameters that have matching types, not just the first.
- Update diff tests.

Fixes #5218.

### CODE REVIEW

**Comment by jimblandy** [comment]
Reviewing the changes to those test files was a bear. Maybe someone should write a program that helps one ignore extraneous differences in... never mind.

File: source/diff/diff.cpp [hunk 1]
```diff
@@ -338,6 +338,30 @@ class Differ {
...
+  // Bucket `src_ids` and `dst_ids` by key ids returned by `get_group`, and
+  // then pair up buckets whose ids map to each other.
+  //
+  // For example, say the input groups are as follows, where `X -> Y` means
+  // that `X` is a member of the `IdGroup` and `get_group` maps `X` to `Y`
+  //
+  // - src_ids: { 1 -> 100, 2 -> 300, 3 -> 100, 4 -> 200 }
+  // - dst_ids: { 5 -> 10, 6 -> 20, 7 -> 10, 8 -> 300 }
+  //
+  // and suppose that the following src/dst ids are paired: 100/10 and 200/20.
```
Comment (ShabbyX) [inline source/diff/diff.cpp:350]: nit: To keep with the terminology used in this file, `s/are paired/are already matched`. It's been a while since I worked on this code, so please ignore if I'd used this terminology elsewhere already.

**Review by ShabbyX — CHANGES_REQUESTED** [review]

**Comment by ShabbyX** [comment]
Not sure if you missed a push, I don't see any diff w.r.t the resolved comments :thinking:

**Comment by jimblandy** [comment]
Sorry, that was just the formatting, I'm working on the comments right now. (Thought I'd resolved them, and then wanted to tweak them a bit more.)

**Comment by jimblandy** [comment]
Okay, I think 6b50a18 should address all comments.

**Review by ShabbyX — APPROVED** [review]

**Comment by jimblandy** [comment]
There's a general didactic principle, "concrete before abstract", so I changed the comment to start with the concrete example of pairing buckets by type. It's supposed to be easier to follow the example when holding that specific use case in mind.

Then I used the verb 'pair' for what one does with buckets, and 'match' for what one does with ids.

**Comment by ShabbyX** [comment]
Nice, thanks.

Eventually, it would be nice to have the id "namespace" (src or dst) find its way to the type (as opposed to just `uint32_t`) such that the compiler would make sure src and dst ids aren't compared directly. Like a `SrcId` and `DstId` type that are distinct to the compiler (although identical)

**Comment by jimblandy** [comment]
@s-perron This is ready to merge.
