### PR TITLE
Use standard function to get stdin to binary mode.

### LINKED ISSUE #2518: spirv-dis succeeds with a filename but fails when reading from stdin
This appears to be broken on Windows:

FAIL:
```
...\vulkansdk\1.1.101.0\bin\spirv-dis < hs_bc_0.spv
error: file does not exist '(null)'
```
OK:
```
c:\vulkansdk\1.1.101.0\bin\spirv-dis  hs_bc_0.spv
; SPIR-V
; Version: 1.3
; Generator: Khronos Glslang Reference Front End; 7
; Bound: 788
; Schema: 0
...
```
The now stale ToT `spirv-dis` has a different failure mode:

FAIL:
```
spirv-dis --version
SPIRV-Tools v2018.5-dev a3e3869540b7c2d2f01c846fc76453be55d1ac34
spirv-dis < hs_bc_0.spv
; SPIR-V
; Version: 1.3
; Generator: Khronos Glslang Reference Front End; 7
; Bound: 788
; Schema: 0
...
error: 1489: End of input reached while decoding OpBitcast starting at word 1487: missing result ID operand at word offset 2.
```

OK
```
spirv-dis  hs_bc_0.spv
; SPIR-V
; Version: 1.3
; Generator: Khronos Glslang Reference Front End; 7
; Bound: 788
; Schema: 0
...
```

_Originally posted by @allanmac in https://github.com/KhronosGroup/SPIRV-Tools/issues/1688#issuecomment-483341331_

### PR DESCRIPTION
**Pull request by s-perron**
The first implementation to try to change stdin to binary mode is not
portable.  Using freopen has a lot of implementation defined behavior,
and the code relied on that working.

Looking into the MSVC documentation, I do not see a portable way of
doing this.  I've implemented a Windows specific method and do nothing
for other systems.  In general, UNIX based systems do make a distinction
between text and binary files, so nothing needs to be done for them.

Fixes #2518

### CODE REVIEW

File: tools/as/as.cpp [hunk 1]
```diff
@@ -129,7 +129,7 @@ int main(int argc, char** argv) {
   }
 
   std::vector<char> contents;
-  if (!ReadFile<char>(inFile, "r", &contents)) return 1;
+  if (!ReadFile<char>(inFile, /* isBinaryFile = */ false, &contents)) return 1;
```
Comment (dneto0) [inline tools/as/as.cpp:132]: nit:  The temptation to use a comment on the parameter expression is a hint that two methods would be easier to use:  ReadBinaryFile and ReadTextFile.

But this MR is a vast improvement over the current situation.  So I won't block on this.

**Review by dneto0 — APPROVED** [review]

File: tools/as/as.cpp (hunk 1 above)
Comment (s-perron) [reply tools/as/as.cpp:132]: good idea, and I need to fix the PR anyway, so I'll do that.
