### PR TITLE
spirv-fuzz: Apply fuzzer pass before checking exit conditions

### LINKED ISSUE #4198: spirv-fuzz: assertion failure in main fuzzing loop if maximum number of transformations is exceeded
In Fuzzer::Run, we check whether the transformation limit has been reached before calling ApplyPassAndCheckValidity. Then we call ShouldContinueRepeatedPasses, which assumes that the transformation limit has not been reached. This can lead to an assertion failing because the logic for deciding with what probability to continue fuzzing depends on the number of transformations applied so far being less than the maximum number of allowed transformations.

@Vasniktel for info.

### PR DESCRIPTION
**Pull request by afd**
Fixes #4198.

### CODE REVIEW

**Comment by afd** [comment]
@Vasniktel was there a good reason why we previously did all the termination checks *before* calling ApplyPassAndCheckValidity? If it doesn't matter then this seems like the simplest fix.

File: source/fuzz/fuzzer.cpp [hunk 1]
```diff
@@ -301,7 +307,9 @@ Fuzzer::Result Fuzzer::Run(uint32_t num_of_transformations_to_apply) {
       break;
     }
 
-    // If the number of transformations is still small
+    // Check that we've not got stuck (this can happen if the only available
```
Comment (Vasniktel) [inline source/fuzz/fuzzer.cpp:310]: Thanks for fixing the comment.

**Review by Vasniktel — APPROVED** [review]

**Comment by Vasniktel** [comment]
I don't think the order of checks matters.
