### PR TITLE
Fix OpDot folding of half float vectors.

### LINKED ISSUE #2405: spirv-opt crashes in const_folding_rules.cpp
When we compile the following HLSL shader:

```hlsl
float4 PS_Main() : SV_Target0 {
	half3 v0 = half3(0, 0, 1);
	float ret = dot(v0, v0);
	return ret;
}
```
to SPIR-V using DXC, it causes a crash in spirv-opt.

If the HLSL shader is compiled **_with optimizations disabled_**, we get the following SPIR-V:
```spir-v
; SPIR-V
; Version: 1.0
; Generator: Google spiregg; 0
; Bound: 28
; Schema: 0
               OpCapability Shader
               OpExtension "SPV_AMD_gpu_shader_half_float"
               OpMemoryModel Logical GLSL450
               OpEntryPoint Fragment %main "main" %out_var_SV_Target0
               OpExecutionMode %main OriginUpperLeft
               OpSource HLSL 620
               OpName %out_var_SV_Target0 "out.var.SV_Target0"
               OpName %main "main"
               OpName %src_main "src.main"
               OpName %bb_entry "bb.entry"
               OpName %v0 "v0"
               OpName %ret "ret"
               OpDecorate %out_var_SV_Target0 Location 0
       %half = OpTypeFloat 16
%half_0x0p_0 = OpConstant %half 0x0p+0
%half_0x1p_0 = OpConstant %half 0x1p+0
     %v3half = OpTypeVector %half 3
          %7 = OpConstantComposite %v3half %half_0x0p_0 %half_0x0p_0 %half_0x1p_0
      %float = OpTypeFloat 32
    %v4float = OpTypeVector %float 4
%_ptr_Output_v4float = OpTypePointer Output %v4float
       %void = OpTypeVoid
         %12 = OpTypeFunction %void
         %16 = OpTypeFunction %v4float
%_ptr_Function_v3half = OpTypePointer Function %v3half
%_ptr_Function_float = OpTypePointer Function %float
%out_var_SV_Target0 = OpVariable %_ptr_Output_v4float Output
       %main = OpFunction %void None %12
         %13 = OpLabel
         %14 = OpFunctionCall %v4float %src_main
               OpStore %out_var_SV_Target0 %14
               OpReturn
               OpFunctionEnd
   %src_main = OpFunction %v4float None %16
   %bb_entry = OpLabel
         %v0 = OpVariable %_ptr_Function_v3half Function
        %ret = OpVariable %_ptr_Function_float Function
               OpStore %v0 %7
         %22 = OpLoad %v3half %v0
         %23 = OpLoad %v3half %v0
         %24 = OpDot %half %22 %23
         %25 = OpFConvert %float %24
               OpStore %ret %25
         %26 = OpLoad %float %ret
         %27 = OpCompositeConstruct %v4float %26 %26 %26 %26
               OpReturnValue %27
               OpFunctionEnd
```

To reproduce the crash, you can run spirv-opt (-O) on the above SPIR-V.

Running:
```
C:\spirv-tools\build\tools\Debug\spirv-opt.exe test.spv -O -o test.optimized.spv
```
Results in:
```
Assertion failed: result_type != nullptr && a != nullptr && b != nullptr, file c:\spirv-tools\source\opt\const_folding_rules.cpp, line 593
```

Note that you need to use the Debug build to reproduce the crash.

Thanks

### PR DESCRIPTION
**Pull request by s-perron**
The code that folds OpDot does not handle half floats correctly.  After
trying to multiple the first components, we get a nullptr because we
don't fold half float values.  This nullptr gets passed to the code that
does the addition, and causes an assert.

Fixes #2405.

### CODE REVIEW

File: source/opt/const_folding_rules.cpp [hunk 1]
```diff
@@ -547,7 +547,7 @@ ConstantFoldingRule FoldOpDotWithConstants() {
     for (int i = 0; i < 2; ++i) {
       if (constants[i]) {
         if (constants[i]->AsNullConstant() ||
-            constants[i]->AsVectorConstant()->IsZero()) {
+            (constants[i]->AsVectorConstant()->IsZero())) {
```
Comment (dnovillo) [inline source/opt/const_folding_rules.cpp]: Needed?

Comment (s-perron) [reply source/opt/const_folding_rules.cpp]: No, I was playing around with other stuff and I did not revert everything.
