### PR TITLE
spirv-fuzz: Fix OutlineFunction in presence of unreachable blocks

### LINKED ISSUE #4298: spirv-fuzz: TransformationOutlineFunction produces invalid binary when unreachable blocks reference outlined blocks
This can be reproduced on 91931ffcd22ae774ed932c98c2d0319db9720d93 with
> spirv-fuzz --replay=transformations.binary original.spv --replay-validation -o replayed.spv

The reason is that some unreachable block references one of the blocks in the outlined region. The instruction in that unreachable block is not updated which causes the following error
> ERROR 0:0:133: Block(s) {36[%36]} are referenced but not defined in function 4[%main]
  %main = OpFunction %void DontInline %3

[data.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/6539663/data.zip)

### PR DESCRIPTION
**Pull request by afd**
This change prevents TransformationOutlineFunction from outlining a
region of blocks if some block in the region has an unreachable
predecessor. This avoids a bug whereby the region would be outlined,
and the unreachable predecessors would be left behind, referring to
blocks that are no longer in the function.

Fixes #4298.

### CODE REVIEW

File: test/fuzz/transformation_outline_function_test.cpp [hunk 1]
```diff
@@ -3207,6 +3207,46 @@ TEST(TransformationOutlineFunctionTest, Miscellaneous4) {
...
+  ASSERT_TRUE(fuzzerutil::IsValidAndWellFormed(context.get(), validator_options,
+                                               kConsoleMessageConsumer));
+  TransformationContext transformation_context(
+      MakeUnique<FactManager>(context.get()), validator_options);
+  TransformationOutlineFunction transformation(5, 5, /* not relevant */ 200,
+                                               100, 101, 102, 103,
+                                               /* not relevant */ 201, {}, {});
+  ASSERT_FALSE(
+      transformation.IsApplicable(context.get(), transformation_context));
+  ApplyAndCheckFreshIds(transformation, context.get(), &transformation_context);
```
Comment (Vasniktel) [inline test/fuzz/transformation_outline_function_test.cpp:3247]: Why do we apply it if it's not applicable?

**Review by Vasniktel — CHANGES_REQUESTED** [review]
Left a comment in tests. Also, do we need to adjust the fuzzer pass as well since we've changed the way we compute single-entry-single-exit region (we probably don't since we use `MaybeApplyTransformation` there)?

File: test/fuzz/transformation_outline_function_test.cpp (hunk 1 above)
Comment (afd) [reply test/fuzz/transformation_outline_function_test.cpp]: Oops, I had meant to delete that line when I adapted the new test from a previous valid one. Fixed.

**Comment by afd** [comment]
Thanks for the comment. We don't need to adapt the fuzzer pass, indeed due to using "maybe".

**Review by Vasniktel — APPROVED** [review]
