### PR TITLE
spirv-fuzz: Fix bug in TransformationDuplicateRegionWithSelection

### LINKED ISSUE #3827: spirv-fuzz: Assertion failure in TransformationDuplicateRegionWithSelection
The following test fails:
```cpp
TEST(A, a) {
  std::string shader = R"(
               OpCapability Shader
          %1 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical GLSL450
               OpEntryPoint Fragment %4 "main"
               OpExecutionMode %4 OriginUpperLeft
               OpSource ESSL 310
          %2 = OpTypeVoid
          %3 = OpTypeFunction %2
         %18 = OpTypeBool
         %50 = OpConstantTrue %18
          %4 = OpFunction %2 None %3
          %6 = OpLabel
               OpBranch %5
          %5 = OpLabel
               OpLoopMerge %9 %8 None
               OpBranchConditional %50 %8 %9
          %8 = OpLabel
               OpBranch %5
          %9 = OpLabel
               OpReturn
               OpFunctionEnd
    )";

  const auto env = SPV_ENV_UNIVERSAL_1_4;
  const auto consumer = nullptr;
  const auto context = BuildModule(env, consumer, shader, kFuzzAssembleOption);
  ASSERT_TRUE(IsValid(env, context.get()));

  FactManager fact_manager;
  spvtools::ValidatorOptions validator_options;
  TransformationContext transformation_context(&fact_manager,
                                               validator_options);

  TransformationDuplicateRegionWithSelection transformation(100, 50, 101, 5, 9, {{{5, 102}, {9, 103}, {8, 104}}}, {}, {});
  ASSERT_TRUE(transformation.IsApplicable(context.get(), transformation_context));
  transformation.Apply(context.get(), &transformation_context);
}
```
with an assertion message

> virtual void spvtools::fuzz::TransformationDuplicateRegionWithSelection::Apply(opt::IRContext *, spvtools::fuzz::TransformationContext *) const: Assertion `entry_block_preds.size() == 1 && "The entry of the region to be duplicated can have only one " "predecessor."' failed.

Can be reproduced on 60ce96e2.

### PR DESCRIPTION
**Pull request by antnkarp**
The following changes are introduced:
1. Entry block might have more than one predecessor, even if it is not a selection/loop merge block. However Apply method asserts that there is only one predecessor. Now, IsApplicable method ensures that there is only one predecessor.
2. In fuzzer pass we exclude both loop headers and selection headers as potential exit blocks.

Fixes #3827

### CODE REVIEW

File: source/fuzz/transformation_duplicate_region_with_selection.cpp [hunk 1]
```diff
@@ -110,6 +110,17 @@ bool TransformationDuplicateRegionWithSelection::IsApplicable(
     return false;
   }
 
+  // To make the process of resolving OpPhi instructions easier, we require that
+  // the entry block has only one predecessor.
+  auto entry_block_preds = ir_context->cfg()->preds(entry_block->id());
+  std::sort(entry_block_preds.begin(), entry_block_preds.end());
+  entry_block_preds.erase(
+      unique(entry_block_preds.begin(), entry_block_preds.end()),
```
Comment (Vasniktel) [inline source/fuzz/transformation_duplicate_region_with_selection.cpp:118]: It would be good if you could add `std::` for `unique` function.

**Review by Vasniktel — APPROVED** [review]

File: test/fuzz/transformation_duplicate_region_with_selection_test.cpp [hunk 2]
```diff
@@ -1680,6 +1680,85 @@ TEST(TransformationDuplicateRegionWithSelectionTest,
...
+               OpReturn
+               OpFunctionEnd
+    )";
+
+  const auto env = SPV_ENV_UNIVERSAL_1_4;
+  const auto consumer = nullptr;
+  const auto context = BuildModule(env, consumer, shader, kFuzzAssembleOption);
+  ASSERT_TRUE(IsValid(env, context.get()));
+
+  FactManager fact_manager;
```
Comment (Vasniktel) [inline test/fuzz/transformation_duplicate_region_with_selection_test.cpp:1749]: I'm not sure why it didn't produce any errors but the fact manager's constructor takes `context.get()` parameter now.

Comment (afd) [reply test/fuzz/transformation_duplicate_region_with_selection_test.cpp:1749]: I guess this will show up when @antnkarp rebases.

Comment (antnkarp) [reply test/fuzz/transformation_duplicate_region_with_selection_test.cpp:1749]: It's the same in tests related to other transformations.

Comment (Vasniktel) [reply test/fuzz/transformation_duplicate_region_with_selection_test.cpp:1749]: Yes. Also, TransformationContext will store the fact manager using a unique pointer after when https://github.com/KhronosGroup/SPIRV-Tools/pull/3844 is merged.

Comment (Vasniktel) [reply test/fuzz/transformation_duplicate_region_with_selection_test.cpp:1749]: @antnkarp I think you forgot to rebase.

Comment (antnkarp) [reply test/fuzz/transformation_duplicate_region_with_selection_test.cpp:1749]: You are right, I'm rebasing now.

Comment (Vasniktel) [reply test/fuzz/transformation_duplicate_region_with_selection_test.cpp:1750]: Thanks. Unfortunately, you'll have to rebase one more time when https://github.com/KhronosGroup/SPIRV-Tools/pull/3844 is merged.

Comment (antnkarp) [reply test/fuzz/transformation_duplicate_region_with_selection_test.cpp:1750]: I have rebased it and pushed to this branch.

Comment (Vasniktel) [reply test/fuzz/transformation_duplicate_region_with_selection_test.cpp:1750]: @antnkarp, can you, please, rebase it once more and fix errors in the test file?
