### PR TITLE
opt/spec_constants: fix bit pattern width checks.

### LINKED ISSUE #4587: 16-bit specialization constants are broken with set_spec_constant_default_value_pass
This pass fails to deal with 8/16-bit spec constants using the bitfield interface.

101	    if (IT->width() == input_bit_pattern.size() * sizeof(uint32_t) * 8) {

(gdb) print *IT
$10 = {<spvtools::opt::analysis::Type> = {_vptr.Type = 0x7ffff7a1b480 <vtable for spvtools::opt::analysis::Integer+16>, 
    decorations_ = std::vector of length 0, capacity 0, kind_ = spvtools::opt::analysis::Type::kInteger}, width_ = 16, signed_ = false}

(gdb) print input_bit_pattern
$11 = std::vector of length 1, capacity 1 = {3000}
(gdb) print input_bit_pattern.size()
$12 = 1
(gdb) print input_bit_pattern.size() * sizeof(uint32_t) * 8
$13 = 32

16 != 32 so it fails. same for the half float one below that.

### PR DESCRIPTION
**Pull request by airlied**
The input bit patterns are always at least 32-bits, so let the test
pass for 8/16-bit values as well. This shouldn't have any effect on the
64-bit patterns I assume this was introduced for.

Closes #4587

### CODE REVIEW

File: source/opt/set_spec_constant_default_value_pass.cpp [hunk 1]
```diff
@@ -98,11 +98,15 @@ std::vector<uint32_t> ParseDefaultValueBitPattern(
     }
     return result;
   } else if (const auto* IT = type->AsInteger()) {
-    if (IT->width() == input_bit_pattern.size() * sizeof(uint32_t) * 8) {
+    auto width = IT->width();
+    if (width == 8 || width == 16) width = 32;
+    if (width == input_bit_pattern.size() * sizeof(uint32_t) * 8) {
```
Comment (dneto0) [inline source/opt/set_spec_constant_default_value_pass.cpp:103]: This is good.

I'd also go with a generalization:

  width = min(width, 32); 

One thing to watch for is that SPIR-V requires literals to fill out upper (unused) bits in a certain way.  From the definition of Literal:

> For a numeric literal, the lower-order words appear first. If a numeric type’s bit width is less than 32-bits, the value appears in the low-order bits of the word, and the high-order bits must be 0 for a floating-point type or integer type with Signedness of 0, or sign extended for an integer type with a Signedness of 1 (similarly for the remaining bits of widths larger than 32 bits but not a multiple of 32 bits).
 
So it's possible to send in invalid data through this API now.
Given that this is a net improvement, I'll approve.
