### PR TITLE
Sink pointer instructions in merge return

### LINKED ISSUE #3030: opt: dEQP-VK.graphicsfuzz.always-false-if-in-do-while
This test fails. To reproduce: 

```
spirv-opt -O -o temp.spv *.spv
spirv-val temp.spv
```

[always-false-if-in-do-while.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/3833312/always-false-if-in-do-while.zip)

### LINKED ISSUE #3266: Merge return producing a phi of pointers
```
               OpCapability Shader
          %1 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical GLSL450
               OpEntryPoint Fragment %2 "main" %3
               OpExecutionMode %2 OriginUpperLeft
               OpDecorate %3 Location 0
               OpMemberDecorate %_struct_4 0 Offset 0
               OpDecorate %_struct_4 Block
               OpDecorate %5 DescriptorSet 0
               OpDecorate %5 Binding 0
       %void = OpTypeVoid
          %7 = OpTypeFunction %void
      %float = OpTypeFloat 32
    %v2float = OpTypeVector %float 2
%_ptr_Function_v2float = OpTypePointer Function %v2float
         %11 = OpTypeFunction %v2float %_ptr_Function_v2float
    %v4float = OpTypeVector %float 4
%_ptr_Output_v4float = OpTypePointer Output %v4float
          %3 = OpVariable %_ptr_Output_v4float Output
    %float_1 = OpConstant %float 1
    %float_0 = OpConstant %float 0
         %16 = OpConstantComposite %v4float %float_1 %float_0 %float_0 %float_1
  %_struct_4 = OpTypeStruct %v2float
%_ptr_Uniform__struct_4 = OpTypePointer Uniform %_struct_4
          %5 = OpVariable %_ptr_Uniform__struct_4 Uniform
        %int = OpTypeInt 32 1
      %int_0 = OpConstant %int 0
       %uint = OpTypeInt 32 0
     %uint_1 = OpConstant %uint 1
%_ptr_Uniform_float = OpTypePointer Uniform %float
       %bool = OpTypeBool
         %24 = OpConstantComposite %v2float %float_1 %float_1
%_ptr_Function_float = OpTypePointer Function %float
      %false = OpConstantFalse %bool
          %2 = OpFunction %void None %7
         %27 = OpLabel
         %28 = OpVariable %_ptr_Function_v2float Function
               OpStore %28 %24
         %29 = OpFunctionCall %v2float %30 %28
               OpReturn
               OpFunctionEnd
         %30 = OpFunction %v2float None %11
         %31 = OpFunctionParameter %_ptr_Function_v2float
         %32 = OpLabel
               OpStore %3 %16
               OpBranch %33
         %33 = OpLabel
               OpLoopMerge %34 %35 None
               OpBranch %36
         %36 = OpLabel
         %37 = OpAccessChain %_ptr_Uniform_float %5 %int_0 %uint_1
         %38 = OpLoad %float %37
         %39 = OpFOrdLessThan %bool %38 %float_0
               OpSelectionMerge %40 None
               OpBranchConditional %39 %41 %35
         %41 = OpLabel
               OpReturnValue %24
         %40 = OpLabel
               OpUnreachable
         %35 = OpLabel
         %42 = OpAccessChain %_ptr_Function_float %31 %uint_1
         %43 = OpLoad %float %42
         %44 = OpFSub %float %43 %float_1
               OpStore %42 %44
               OpBranchConditional %false %33 %34
         %34 = OpLabel
         %45 = OpLoad %float %42
         %46 = OpFSub %float %45 %float_1
               OpStore %42 %46
               OpReturnValue %24
               OpFunctionEnd
```

Run `--merge-return` and validate the results. Should see the error:
>error: line 78: Using pointers with OpPhi requires capability VariablePointers or VariablePointersStorageBuffer
>  %58 = OpPhi %_ptr_Function_float %57 %41 %57 %40 %42 %35

Merge return is introducing a phi of Function scope pointers.  The validator message isn't great here (being improved in an open PR), but merge return shouldn't generate this code.

### PR DESCRIPTION
**Pull request by s-perron**
We cannot create an OpPhi for pointers, so we have to regenerate these
instructions instead.

Fixes #3030
Fixes #3266

### CODE REVIEW

File: source/opt/merge_return_pass.cpp [hunk 1]
```diff
@@ -318,7 +315,39 @@ void MergeReturnPass::CreatePhiNodesForInst(BasicBlock* merge_block,
...
 
-    Instruction* new_phi = builder.AddPhi(inst.type_id(), phi_operands);
+    Instruction* new_phi = nullptr;
+    // If the instruction is a pointer and variable pointers are not an option,
+    // then we have to regenerate the instruction instead of creating an OpPhi
+    // instruction.  If not, the Spir-V will be invalid.
+    bool regenerateInstruction =
+        get_def_use_mgr()->GetDef(inst.type_id())->opcode() == SpvOpTypePointer;
+    regenerateInstruction &= !context()->get_feature_mgr()->HasCapability(
+        SpvCapabilityVariablePointers);
```
Comment (alan-baker) [inline source/opt/merge_return_pass.cpp:325]: Variable pointers are only allowed for Workgroup and StorageBuffer storage classes. You should probably tighten the restriction.

Comment (s-perron) [reply source/opt/merge_return_pass.cpp]: Done.
