### PR TITLE
Add pass to fix some invalid unreachable blocks for WebGPU

### LINKED ISSUE #2429: WebGPU transform: split a block that is unreachable and both a merge block and continue target
This is required because unreachable merge must end with OpUnreachable, but unreachable continue target must end with OpBranch.

### PR DESCRIPTION
**Pull request by zoddicus**
Attempts to split up unreachable blocks that are used both as a
merge-block and a continue-target.

Fixes #2429

### CODE REVIEW

File: source/opt/optimizer.cpp [hunk 1]
```diff
@@ -873,4 +874,9 @@ Optimizer::PassToken CreateDecomposeInitializedVariablesPass() {
       MakeUnique<opt::DecomposeInitializedVariablesPass>());
 }
 
+Optimizer::PassToken CreateSplitInvalidUnreachablePass() {
```
Comment (s-perron) [inline source/opt/optimizer.cpp]: Do you add command line options for the passes you are adding?  They are useful and should be added.

File: source/opt/split_invalid_unreachable_pass.cpp [hunk 2]
```diff
@@ -0,0 +1,87 @@
...
+              std::unique_ptr<BasicBlock> new_block(
+                  new BasicBlock(std::move(new_label)));
+              auto* block_ptr = new_block.get();
+              InstructionBuilder builder(
+                  context(), new_block.get(),
+                  IRContext::kAnalysisDefUse |
+                      IRContext::kAnalysisInstrToBlockMapping);
+              builder.AddUnreachable();
+              cfg()->RegisterBlock(block_ptr);
+              (&*func)->AddBasicBlock(std::move(new_block));
```
Comment (s-perron) [inline source/opt/split_invalid_unreachable_pass.cpp]: It will look awkward when people look at the spir-v because the merge block will be at the end of the function.  It is not necessary, but it might be best to insert the new block before `unreachable`.

Comment (zoddicus) [reply source/opt/split_invalid_unreachable_pass.cpp]: Done

File: source/opt/optimizer.cpp (hunk 1 above)
Comment (zoddicus) [reply source/opt/optimizer.cpp]: Created #2574 to track implementing this.

**Comment by zoddicus** [comment]
Committed before the bots completed because the last patch was just running the formatter and all the other checks had passed.
