### PR TITLE
Create a pass to work around a driver bug related to OpUnreachable.

### LINKED ISSUE #1209: Work around a driver bug related to OpUnreachable
Add a pass to work around the issue https://gitlab.khronos.org/Tracker/vk-gl-cts/issues/952.

The solution will be to change OpUnreachable into a branch to the merge block of its nearest enclosing loop, if one exists.

An example shader is

```
               OpCapability Shader
          %1 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical GLSL450
               OpEntryPoint Vertex %main "main" %texcoord %gl_VertexIndex %_
               OpSource GLSL 400
               OpSourceExtension "GL_ARB_separate_shader_objects"
               OpSourceExtension "GL_ARB_shading_language_420pack"
               OpName %main "main"
               OpName %texcoord "texcoord"
               OpName %buf "buf"
               OpMemberName %buf 0 "MVP"
               OpMemberName %buf 1 "position"
               OpMemberName %buf 2 "attr"
               OpName %ubuf "ubuf"
               OpName %gl_VertexIndex "gl_VertexIndex"
               OpName %gl_PerVertex "gl_PerVertex"
               OpMemberName %gl_PerVertex 0 "gl_Position"
               OpName %_ ""
               OpDecorate %texcoord Location 0
               OpDecorate %_arr_v4float_uint_72 ArrayStride 16
               OpDecorate %_arr_v4float_uint_72_0 ArrayStride 16
               OpMemberDecorate %buf 0 ColMajor
               OpMemberDecorate %buf 0 Offset 0
               OpMemberDecorate %buf 0 MatrixStride 16
               OpMemberDecorate %buf 1 Offset 64
               OpMemberDecorate %buf 2 Offset 1216
               OpDecorate %buf Block
               OpDecorate %ubuf DescriptorSet 0
               OpDecorate %ubuf Binding 0
               OpDecorate %gl_VertexIndex BuiltIn VertexIndex
               OpMemberDecorate %gl_PerVertex 0 BuiltIn Position
               OpDecorate %gl_PerVertex Block
       %void = OpTypeVoid
         %13 = OpTypeFunction %void
      %float = OpTypeFloat 32
    %v4float = OpTypeVector %float 4
%_ptr_Output_v4float = OpTypePointer Output %v4float
   %texcoord = OpVariable %_ptr_Output_v4float Output
%mat4v4float = OpTypeMatrix %v4float 4
       %uint = OpTypeInt 32 0
    %uint_72 = OpConstant %uint 72
%_arr_v4float_uint_72 = OpTypeArray %v4float %uint_72
%_arr_v4float_uint_72_0 = OpTypeArray %v4float %uint_72
        %buf = OpTypeStruct %mat4v4float %_arr_v4float_uint_72 %_arr_v4float_uint_72_0
%_ptr_Uniform_buf = OpTypePointer Uniform %buf
       %ubuf = OpVariable %_ptr_Uniform_buf Uniform
        %int = OpTypeInt 32 1
      %int_2 = OpConstant %int 2
%_ptr_Input_int = OpTypePointer Input %int
%gl_VertexIndex = OpVariable %_ptr_Input_int Input
%_ptr_Uniform_v4float = OpTypePointer Uniform %v4float
%gl_PerVertex = OpTypeStruct %v4float
%_ptr_Output_gl_PerVertex = OpTypePointer Output %gl_PerVertex
          %_ = OpVariable %_ptr_Output_gl_PerVertex Output
      %int_0 = OpConstant %int 0
      %int_1 = OpConstant %int 1
    %float_1 = OpConstant %float 1
         %30 = OpConstantComposite %v4float %float_1 %float_1 %float_1 %float_1
       %main = OpFunction %void None %13
         %32 = OpLabel
               OpBranch %33
         %33 = OpLabel
               OpLoopMerge %34 %35 None
               OpBranch %36
         %36 = OpLabel
               OpSelectionMerge %37 None
               OpSwitch %int_1 %38
         %38 = OpLabel
         %39 = OpLoad %int %gl_VertexIndex
         %40 = OpAccessChain %_ptr_Uniform_v4float %ubuf %int_2 %39
         %41 = OpLoad %v4float %40
               OpStore %texcoord %41
         %48 = OpAccessChain %_ptr_Output_v4float %_ %int_0
               OpStore %48 %30
               OpBranch %34
         %37 = OpLabel
               OpUnreachable
         %35 = OpLabel
               OpBranch %33
         %34 = OpLabel
               OpReturn
               OpFunctionEnd
```

### PR DESCRIPTION
**Pull request by s-perron**
We have come across a driver bug where and OpUnreachable inside a loop
is causing the shader to go into an infinite loop.  This commit will try
to avoid this bug by turning OpUnreachable instructions that are
contained in a loop into branches to the loop merge block.

This is not added to "-O" and "-Os" because it should only be used if
the driver being targeted has this problem.

Fixes #1209.

### CODE REVIEW

**Comment by s-perron** [comment]
Still need to add test.

File: include/spirv-tools/optimizer.hpp [hunk 1]
```diff
@@ -475,6 +475,12 @@ Optimizer::PassToken CreatePrivateToLocalPass();
 // and computations with constant operands.
 Optimizer::PassToken CreateCCPPass();
 
+// Creates a workaround driver bugs pass.  This pass attempts to work around
+// known driver bugs by identifying the bad code sequences and rewriting them.
+//
+// Current workarounds: avoid OpUnreachable instructions in loops.
+Optimizer::PassToken CreateWorkaroundPass();
```
Comment (dneto0) [inline include/spirv-tools/optimizer.hpp]: Bikeshedding: I'd like this to be more specific than just "workaround"
I'd rather have  "CreateWorkaround1209Pass"

We may end up with 5 workaround that have various subsets targeted at different particular drivers.  So keeping it specific and separable is preferable.  Even if the name is embarrassing.

File: source/opt/workaround.cpp [hunk 2]
```diff
@@ -0,0 +1,68 @@
+// Copyright (c) 2017 Google Inc.
```
Comment (dneto0) [inline source/opt/workaround.cpp]: 2018

File: source/opt/workaround.h [hunk 3]
```diff
@@ -0,0 +1,41 @@
...
+
+#include "pass.h"
+
+namespace spvtools {
+namespace opt {
+
+// See optimizer.hpp for documentation.
+class WorkaroundDriverBugs : public Pass {
+ public:
+  const char* name() const override { return "workaround-dirver-bugs"; }
```
Comment (dneto0) [inline source/opt/workaround.h]: "driver".
But I'd rather this be workaround-1209

File: tools/opt/opt.cpp [hunk 4]
```diff
@@ -253,6 +253,10 @@ Options (in lexicographical order):
                Replaces instructions with equivalent and less expensive ones.
   --strip-debug
                Remove all debug instructions.
+  --workaround-dirver-bugs
```
Comment (dneto0) [inline tools/opt/opt.cpp]: Prefer "--workaround-1209"

File: tools/opt/opt.cpp [hunk 5]
```diff
@@ -441,6 +445,8 @@ OptStatus ParseFlags(int argc, const char** argv, Optimizer* optimizer,
         optimizer->RegisterPass(CreatePrivateToLocalPass());
       } else if (0 == strcmp(cur_arg, "--remove-duplicates")) {
         optimizer->RegisterPass(CreateRemoveDuplicatesPass());
+      } else if (0 == strcmp(cur_arg, "--workaround-dirver-bugs")) {
```
Comment (dneto0) [inline tools/opt/opt.cpp]: "workaround-1209"

File: source/opt/workaround.cpp (hunk 2 above)
Comment (s-perron) [reply source/opt/workaround.cpp]: done

File: source/opt/workaround.h (hunk 3 above)
Comment (s-perron) [reply source/opt/workaround.h]: done

File: tools/opt/opt.cpp (hunk 4 above)
Comment (s-perron) [reply tools/opt/opt.cpp]: done

File: tools/opt/opt.cpp (hunk 5 above)
Comment (s-perron) [reply tools/opt/opt.cpp]: done

File: test/opt/workaround1209_test.cpp [hunk 6]
```diff
@@ -0,0 +1,421 @@
...
+          %_ = OpVariable %_ptr_Output_gl_PerVertex Output
+      %int_0 = OpConstant %int 0
+      %int_1 = OpConstant %int 1
+    %float_1 = OpConstant %float 1
+         %28 = OpConstantComposite %v4float %float_1 %float_1 %float_1 %float_1
+       %main = OpFunction %void None %12
+         %29 = OpLabel
+               OpBranch %30
+         %30 = OpLabel
+; CHECK: OpLoopMerge [[merge:%[a-zA-Z_\d]+]]
```
Comment (dneto0) [inline test/opt/workaround1209_test.cpp]: FYI   you can use %\w+  as the pattern for a disassembled ID.   Effcee's RE2 pattern matcher is more expressive than FileCheck's

File: source/opt/CMakeLists.txt [hunk 7]
```diff
@@ -71,6 +71,7 @@ add_library(SPIRV-Tools-opt
   types.h
   unify_const_pass.h
   value_number_table.h
+        workaround1209.h
```
Comment (alan-baker) [inline source/opt/CMakeLists.txt]: formatting looks funny

File: source/opt/CMakeLists.txt [hunk 8]
```diff
@@ -127,6 +128,7 @@ add_library(SPIRV-Tools-opt
   types.cpp
   unify_const_pass.cpp
   value_number_table.cpp
+        workaround1209.cpp
```
Comment (alan-baker) [inline source/opt/CMakeLists.txt]: here too

File: source/opt/CMakeLists.txt (hunk 7 above)
Comment (s-perron) [reply source/opt/CMakeLists.txt]: Fixed.  The formater in the IDE messes up the cmake files every time.  I think it is because it adds a tab.

**Comment by dneto0** [comment]
Android build still failing?

File: Android.mk [hunk 9]
```diff
@@ -108,7 +108,8 @@ SPVTOOLS_OPT_SRC_FILES := \
 		source/opt/type_manager.cpp \
 		source/opt/types.cpp \
 		source/opt/unify_const_pass.cpp \
-		source/opt/value_number_table.cpp
+		source/opt/value_number_table.cpp \
+		source/opt/workaround.cpp
```
Comment (dneto0) [inline Android.mk]: This has to be workaround1209.cpp now

**Comment by s-perron** [comment]
I'll merge if all of the test pass.
