### PR TITLE
spirv-fuzz: Fix to TransformationDuplicateRegionWithSelection

### LINKED ISSUE #3940: spirv-fuzz: Problem with exit block terminators in TransformationDuplicateRegionWithSelection
If a region ends with a block terminated by OpReturnValue or OpBranchConditional, and if the terminator uses an id defined in the region, then currently the transformed terminator uses the id defined in one part of the duplicated selection.  It should instead use the id defined by the OpPhi that reconciles output ids from the two duplicated parts.

### PR DESCRIPTION
**Pull request by afd**
Also incorporates a few style fixes.

Fixes #3940.

### CODE REVIEW

File: test/fuzz/transformation_duplicate_region_with_selection_test.cpp [hunk 1]
```diff
@@ -2015,6 +2015,232 @@ TEST(TransformationDuplicateRegionWithSelectionTest,
...
+               OpFunctionEnd
+        )";
+
+  ASSERT_TRUE(IsEqual(env, expected_shader, context.get()));
+}
+
+TEST(TransformationDuplicateRegionWithSelectionTest,
+     RegionExitUsesOpReturnValueWithIdDefinedInRegion) {
+  // Checks the case where the exit block of a region ends with
+  // OpBranchConditional (but is not a header).
```
Comment (paulthomson) [inline test/fuzz/transformation_duplicate_region_with_selection_test.cpp:2154]: Is this comment wrong?

**Review by paulthomson — APPROVED** [review]

File: test/fuzz/transformation_duplicate_region_with_selection_test.cpp (hunk 1 above)
Comment (afd) [reply test/fuzz/transformation_duplicate_region_with_selection_test.cpp]: Fixed, thanks.
