### PR TITLE
Reject folding comparisons with unfoldable types.

### LINKED ISSUE #3343: spirv-opt --ccp error
When i apply the command `spirv-opt  --ccp` in the code below, I receive this error message:

> enrique@enrique-VirtualBox:~/Escritorio/OpenCL-SPIRV_Optimizer/Generated/SPV_Lists/kernels/longest_1895$ spirv-opt --ccp longest_1895.spv -o longest_1895_0.spv
> spirv-opt: ../source/opt/constants.h:195: uint32_t spvtools::opt::analysis::IntConstant::GetU32BitValue() const: Assertion `words().size() == 1' failed.
> Aborted (`core' generated)

Disassembled code of longest_1895.spv (spirv-dis):
; SPIR-V
; Version: 1.0
; Generator: Khronos LLVM/SPIR-V Translator; 14
; Bound: 117
; Schema: 0
               OpCapability Addresses
               OpCapability Linkage
               OpCapability Kernel
               OpCapability Int64
               OpCapability Int8
          %1 = OpExtInstImport "OpenCL.std"
               OpMemoryModel Physical64 OpenCL
               OpEntryPoint Kernel %13 "A" %__spirv_BuiltInGlobalInvocationId %__spirv_BuiltInGlobalSize %__spirv_BuiltInLocalInvocationId
        %113 = OpString "kernel_arg_type.A.float*,float*,float*,int,"
               OpSource OpenCL_C 200000
               OpName %__spirv_BuiltInGlobalInvocationId "__spirv_BuiltInGlobalInvocationId"
               OpName %__spirv_BuiltInGlobalSize "__spirv_BuiltInGlobalSize"
               OpName %__spirv_BuiltInLocalInvocationId "__spirv_BuiltInLocalInvocationId"
               OpName %a "a"
               OpName %b "b"
               OpName %c "c"
               OpName %d "d"
               OpName %entry "entry"
               OpName %land_lhs_true "land.lhs.true"
               OpName %land_lhs_true23 "land.lhs.true23"
               OpName %if_then "if.then"
               OpName %if_end "if.end"
               OpName %a_addr "a.addr"
               OpName %b_addr "b.addr"
               OpName %c_addr "c.addr"
               OpName %d_addr "d.addr"
               OpName %e "e"
               OpName %f "f"
               OpName %g "g"
               OpName %h "h"
               OpName %i "i"
               OpName %j "j"
               OpName %call "call"
               OpName %conv "conv"
               OpName %call1 "call1"
               OpName %conv2 "conv2"
               OpName %call3 "call3"
               OpName %conv4 "conv4"
               OpName %conv5 "conv5"
               OpName %call6 "call6"
               OpName %conv7 "conv7"
               OpName %mul "mul"
               OpName %add "add"
               OpName %conv8 "conv8"
               OpName %call9 "call9"
               OpName %conv10 "conv10"
               OpName %call11 "call11"
               OpName %conv12 "conv12"
               OpName %call13 "call13"
               OpName %conv14 "conv14"
               OpName %idxprom "idxprom"
               OpName %arrayidx "arrayidx"
               OpName %call15 "call15"
               OpName %conv16 "conv16"
               OpName %rem "rem"
               OpName %conv17 "conv17"
               OpName %rem18 "rem18"
               OpName %cmp "cmp"
               OpName %call20 "call20"
               OpName %cmp21 "cmp21"
               OpName %conv24 "conv24"
               OpName %call25 "call25"
               OpName %sub "sub"
               OpName %cmp26 "cmp26"
               OpName %conv28 "conv28"
               OpName %div "div"
               OpName %mul29 "mul29"
               OpName %add30 "add30"
               OpName %idxprom31 "idxprom31"
               OpName %arrayidx32 "arrayidx32"
               OpDecorate %114 Constant
        %114 = OpDecorationGroup
               OpDecorate %115 Alignment 4
        %115 = OpDecorationGroup
               OpDecorate %116 Alignment 8
        %116 = OpDecorationGroup
               OpDecorate %__spirv_BuiltInLocalInvocationId BuiltIn LocalInvocationId
               OpDecorate %__spirv_BuiltInGlobalInvocationId BuiltIn GlobalInvocationId
               OpDecorate %__spirv_BuiltInGlobalSize BuiltIn GlobalSize
               OpDecorate %__spirv_BuiltInGlobalSize LinkageAttributes "__spirv_BuiltInGlobalSize" Import
               OpDecorate %__spirv_BuiltInGlobalInvocationId LinkageAttributes "__spirv_BuiltInGlobalInvocationId" Import
               OpDecorate %__spirv_BuiltInLocalInvocationId LinkageAttributes "__spirv_BuiltInLocalInvocationId" Import
               OpGroupDecorate %114 %__spirv_BuiltInGlobalInvocationId %__spirv_BuiltInGlobalSize %__spirv_BuiltInLocalInvocationId
               OpGroupDecorate %115 %d_addr %e %f %g %h %i %j
               OpGroupDecorate %116 %a_addr %b_addr %c_addr
      %ulong = OpTypeInt 64 0
       %uint = OpTypeInt 32 0
      %uchar = OpTypeInt 8 0
    %ulong_0 = OpConstant %ulong 0
    %ulong_1 = OpConstant %ulong 1
    %v3ulong = OpTypeVector %ulong 3
%_ptr_Input_v3ulong = OpTypePointer Input %v3ulong
       %void = OpTypeVoid
      %float = OpTypeFloat 32
%_ptr_CrossWorkgroup_float = OpTypePointer CrossWorkgroup %float
         %12 = OpTypeFunction %void %_ptr_CrossWorkgroup_float %_ptr_CrossWorkgroup_float %_ptr_CrossWorkgroup_float %uint
%_ptr_Function__ptr_CrossWorkgroup_float = OpTypePointer Function %_ptr_CrossWorkgroup_float
%_ptr_Function_uint = OpTypePointer Function %uint
%_ptr_Function_uchar = OpTypePointer Function %uchar
       %bool = OpTypeBool
%__spirv_BuiltInGlobalInvocationId = OpVariable %_ptr_Input_v3ulong Input
%__spirv_BuiltInGlobalSize = OpVariable %_ptr_Input_v3ulong Input
%__spirv_BuiltInLocalInvocationId = OpVariable %_ptr_Input_v3ulong Input
    %float_1 = OpConstant %float 1
         %13 = OpFunction %void None %12
          %a = OpFunctionParameter %_ptr_CrossWorkgroup_float
          %b = OpFunctionParameter %_ptr_CrossWorkgroup_float
          %c = OpFunctionParameter %_ptr_CrossWorkgroup_float
          %d = OpFunctionParameter %uint
      %entry = OpLabel
     %a_addr = OpVariable %_ptr_Function__ptr_CrossWorkgroup_float Function
     %b_addr = OpVariable %_ptr_Function__ptr_CrossWorkgroup_float Function
     %c_addr = OpVariable %_ptr_Function__ptr_CrossWorkgroup_float Function
     %d_addr = OpVariable %_ptr_Function_uint Function
          %e = OpVariable %_ptr_Function_uint Function
          %f = OpVariable %_ptr_Function_uint Function
          %g = OpVariable %_ptr_Function_uint Function
          %h = OpVariable %_ptr_Function_uint Function
          %i = OpVariable %_ptr_Function_uint Function
          %j = OpVariable %_ptr_Function_uint Function
               OpStore %a_addr %a Aligned 8
               OpStore %b_addr %b Aligned 8
               OpStore %c_addr %c Aligned 8
               OpStore %d_addr %d Aligned 4
         %37 = OpBitcast %_ptr_Function_uchar %e
               OpLifetimeStart %37 4
         %38 = OpLoad %v3ulong %__spirv_BuiltInGlobalInvocationId
       %call = OpCompositeExtract %ulong %38 0
       %conv = OpUConvert %uint %call
               OpStore %e %conv Aligned 4
         %41 = OpBitcast %_ptr_Function_uchar %f
               OpLifetimeStart %41 4
         %42 = OpLoad %v3ulong %__spirv_BuiltInGlobalInvocationId
      %call1 = OpCompositeExtract %ulong %42 1
      %conv2 = OpUConvert %uint %call1
               OpStore %f %conv2 Aligned 4
         %45 = OpBitcast %_ptr_Function_uchar %g
               OpLifetimeStart %45 4
         %46 = OpLoad %v3ulong %__spirv_BuiltInGlobalSize
      %call3 = OpCompositeExtract %ulong %46 0
      %conv4 = OpUConvert %uint %call3
               OpStore %g %conv4 Aligned 4
         %49 = OpBitcast %_ptr_Function_uchar %h
               OpLifetimeStart %49 4
         %50 = OpLoad %uint %g Aligned 4
      %conv5 = OpSConvert %ulong %50
         %52 = OpLoad %v3ulong %__spirv_BuiltInGlobalSize
      %call6 = OpCompositeExtract %ulong %52 1
         %54 = OpLoad %uint %e Aligned 4
      %conv7 = OpSConvert %ulong %54
        %mul = OpIMul %ulong %call6 %conv7
        %add = OpIAdd %ulong %conv5 %mul
      %conv8 = OpUConvert %uint %add
               OpStore %h %conv8 Aligned 4
         %59 = OpBitcast %_ptr_Function_uchar %i
               OpLifetimeStart %59 4
         %60 = OpLoad %v3ulong %__spirv_BuiltInGlobalInvocationId
      %call9 = OpCompositeExtract %ulong %60 1
     %conv10 = OpUConvert %uint %call9
               OpStore %i %conv10 Aligned 4
         %63 = OpBitcast %_ptr_Function_uchar %j
               OpLifetimeStart %63 4
         %64 = OpLoad %v3ulong %__spirv_BuiltInLocalInvocationId
     %call11 = OpCompositeExtract %ulong %64 1
     %conv12 = OpUConvert %uint %call11
               OpStore %j %conv12 Aligned 4
         %67 = OpLoad %v3ulong %__spirv_BuiltInGlobalSize
     %call13 = OpCompositeExtract %ulong %67 0
     %conv14 = OpConvertUToF %float %call13
         %70 = OpLoad %_ptr_CrossWorkgroup_float %a_addr Aligned 8
         %71 = OpLoad %uint %e Aligned 4
    %idxprom = OpSConvert %ulong %71
   %arrayidx = OpInBoundsPtrAccessChain %_ptr_CrossWorkgroup_float %70 %idxprom
               OpStore %arrayidx %conv14 Aligned 4
         %74 = OpLoad %v3ulong %__spirv_BuiltInGlobalInvocationId
     %call15 = OpCompositeExtract %ulong %74 1
         %76 = OpLoad %uint %g Aligned 4
     %conv16 = OpSConvert %ulong %76
        %rem = OpUMod %ulong %call15 %conv16
         %79 = OpLoad %uint %h Aligned 4
     %conv17 = OpSConvert %ulong %79
      %rem18 = OpUMod %ulong %rem %conv17
        %cmp = OpULessThan %bool %rem18 %ulong_0
               OpBranchConditional %cmp %land_lhs_true %if_end
%land_lhs_true = OpLabel
         %85 = OpLoad %v3ulong %__spirv_BuiltInGlobalInvocationId
     %call20 = OpCompositeExtract %ulong %85 0
      %cmp21 = OpUGreaterThanEqual %bool %call20 %ulong_0
               OpBranchConditional %cmp21 %land_lhs_true23 %if_end
%land_lhs_true23 = OpLabel
         %88 = OpLoad %uint %d_addr Aligned 4
     %conv24 = OpSConvert %ulong %88
         %90 = OpLoad %v3ulong %__spirv_BuiltInGlobalSize
     %call25 = OpCompositeExtract %ulong %90 0
        %sub = OpISub %ulong %call25 %ulong_1
      %cmp26 = OpULessThan %bool %conv24 %sub
               OpBranchConditional %cmp26 %if_then %if_end
    %if_then = OpLabel
         %95 = OpLoad %uint %f Aligned 4
     %conv28 = OpConvertSToF %float %95
        %div = OpFDiv %float %float_1 %conv28
         %99 = OpLoad %_ptr_CrossWorkgroup_float %b_addr Aligned 8
        %100 = OpLoad %uint %g Aligned 4
        %101 = OpLoad %uint %d_addr Aligned 4
        %102 = OpLoad %uint %d_addr Aligned 4
      %mul29 = OpIMul %uint %101 %102
      %add30 = OpIAdd %uint %100 %mul29
  %idxprom31 = OpSConvert %ulong %add30
 %arrayidx32 = OpInBoundsPtrAccessChain %_ptr_CrossWorkgroup_float %99 %idxprom31
               OpStore %arrayidx32 %div Aligned 4
               OpBranch %if_end
     %if_end = OpLabel
        %107 = OpBitcast %_ptr_Function_uchar %j
               OpLifetimeStop %107 4
        %108 = OpBitcast %_ptr_Function_uchar %i
               OpLifetimeStop %108 4
        %109 = OpBitcast %_ptr_Function_uchar %h
               OpLifetimeStop %109 4
        %110 = OpBitcast %_ptr_Function_uchar %g
               OpLifetimeStop %110 4
        %111 = OpBitcast %_ptr_Function_uchar %f
               OpLifetimeStop %111 4
        %112 = OpBitcast %_ptr_Function_uchar %e
               OpLifetimeStop %112 4
               OpReturn
               OpFunctionEnd

### PR DESCRIPTION
**Pull request by dnovillo**
When CCP is evaluating an instruction, it was trying to fold a
comparison with 64 bit integers.  This was causing a fold failure later
since the folder still cannot deal with 64 bit integers.

Fixes #3343.

### CODE REVIEW

File: source/opt/instruction.cpp [hunk 1]
```diff
@@ -623,7 +623,23 @@ bool Instruction::IsFoldableByFoldScalar() const {
...
-  return folder.IsFoldableType(type);
+  if (!folder.IsFoldableType(type)) {
+    return false;
+  }
+
+  // Even if the type of the instruction is foldable, its operands may not be
+  // foldable (e.g., comparisons of 64bit types).  Check that all operand types
+  // are foldable before accepting the instruction.
+  bool all_operands_are_foldable = true;
+  ForEachInOperand(
```
Comment (s-perron) [inline source/opt/instruction.cpp:634]: Use `WhileEachInOperand` instead.

File: test/opt/ccp_test.cpp [hunk 2]
```diff
@@ -925,6 +925,43 @@ TEST_F(CCPTest, FoldWithDecoration) {
   SinglePassRunAndMatch<CCPPass>(text, true);
 }
 
+// Reduced from https://github.com/KhronosGroup/SPIRV-Tools/issues/3343.
+// Comparisons using 64-bit types should not be foldable even if their operands
+// are constant.
+TEST_F(CCPTest, Reject64BitComparisons) {
```
Comment (s-perron) [inline test/opt/ccp_test.cpp:931]: I don't think the test should be here.  We should be testing the instruction folder to make sure it does the right thing.  This is a bug in the instruction folder that was fixed in code that is called from the instruction folder.  Add the test to the `IntegerArithmeticTestCases` in the fold_test.cpp.

Comment (dnovillo) [reply test/opt/ccp_test.cpp:931]: Thanks.  Moved.

File: source/opt/instruction.cpp (hunk 1 above)
Comment (dnovillo) [reply source/opt/instruction.cpp]: Done.

**Comment by dnovillo** [comment]
Thanks for the quick review.  PTAL.

File: test/opt/fold_test.cpp [hunk 3]
```diff
@@ -3297,7 +3297,16 @@ INSTANTIATE_TEST_SUITE_P(IntegerArithmeticTestCases, GeneralInstructionFoldingTe
             "%2 = OpIMul %int %3 %int_1\n" +
             "OpReturn\n" +
             "OpFunctionEnd",
-        2, 3)
+        2, 3),
+    // Test case 20: Don't fold comparisons of 64-bit types
```
Comment (s-perron) [inline test/opt/fold_test.cpp:3301]: This looks like test case 42.  I do that to make it easy to find the test case when it fails.  The output will tell you the test number of the test that failed.

Comment (dnovillo) [reply test/opt/fold_test.cpp]: Ah, yes, I had initially tried to make it a bool folding test, but that did not work well.
