### PR TITLE
spirv-fuzz: Check integer and float width capabilities

### LINKED ISSUE #3669: spirv-fuzz: Fuzzed shader invalidation due missing Float64 capability
`spirv-val` invalidated a fuzzed shader because a 64-bit float type was declared but the `Float64` capability was missing.
```
error: line 67: Using a 64-bit floating point type requires the Float64 capability.
  %double = OpTypeFloat 64
```
Debugging `spirv-fuzz`, I found that `TransformationAddTypeFloat` adds 16-bit and 64-bit float types without adding the corresponding `Float16` and `Float64` capabilities.

### PR DESCRIPTION
**Pull request by andreperezmaselco**
`TransformationAddTypeFloat` and `TransformationAddTypeInt` did not check whether the required capabilities were present when adding 16-bit, 64-bit, and 8-bit types.

This change adds these checks in the `IsApplicable` method of each transformation.

Fixes #3669.

### CODE REVIEW

**Comment by Vasniktel** [comment]
It would be good to add simple tests.

File: source/fuzz/transformation_add_type_float.cpp [hunk 1]
```diff
@@ -36,6 +36,15 @@ bool TransformationAddTypeFloat::IsApplicable(
...
   }
 
+  // If the float type width is 16 or 64, then the corresponding Float16 or
+  // Float64 capability must be present.
+  if ((message_.width() == 16 &&
+       !ir_context->get_feature_mgr()->HasCapability(SpvCapabilityFloat16)) ||
+      (message_.width() == 64 &&
+       !ir_context->get_feature_mgr()->HasCapability(SpvCapabilityFloat64))) {
+    return false;
+  }
```
Comment (paulthomson) [inline source/fuzz/transformation_add_type_float.cpp:46]: This is really nice. Sorry to not have suggested this sooner, but could you do a switch statement on the width, include cases for all expected widths (16, 32, 64, (and 8 for int)) where the 32 case just has a break with a comment saying something like `// No capabilities needed.` And then in the default case do:

```
assert(false && "Unexpected float type width");
return false;
```

Or something like that. And do the same for TransformationAddTypeInt.

Comment (andreperezmaselco) [reply source/fuzz/transformation_add_type_float.cpp]: Done.
