### PR TITLE
spirv-fuzz: Add image sample unused components transformation

### LINKED ISSUE #3375: spirv-fuzz: Add unused components to image instructions
We had a bug report that ended up being triggered by an image instruction having unused components in the coordinate. The SPIR-V spec for image instructions has language like:

> Coordinate must be a scalar or vector of floating-point type or integer type. It contains (u[, v] … [, array layer]) as needed by the definition of Sampled Image. Unless the Kernel capability is being used, it must be floating point. **It may be a vector larger than needed, but all unused components will appear after all used components.**

Adding unused components seems ideally suited for the fuzzer.

### PR DESCRIPTION
**Pull request by andreperezmaselco**
Fixes #3375.

### CODE REVIEW

File: source/fuzz/fuzzer_pass_add_image_sample_unused_components.cpp [hunk 1]
```diff
@@ -0,0 +1,142 @@
...
+                : FindOrCreateVectorType(
+                      GetIRContext()->get_type_mgr()->GetId(
+                          coordinate_type->AsVector()->element_type()),
+                      unused_component_count);
+        break;
+      default:
+        break;
+    }
+
+    // Gets |coordinate_type| again because the module has changed.
```
Comment (afd) [inline source/fuzz/fuzzer_pass_add_image_sample_unused_components.cpp:107]: "because the module has changed." -> "because the module may have changed due to the use of FindOrCreateVectorType above."

File: source/fuzz/fuzzer_pass_add_image_sample_unused_components.cpp [hunk 2]
```diff
@@ -0,0 +1,142 @@
...
+    if (!spvOpcodeIsImageSample(instruction->opcode())) {
+      return;
+    }
+
+    if (!GetFuzzerContext()->ChoosePercentage(
+            GetFuzzerContext()
+                ->GetChanceOfAddingImageSampleUnusedComponents())) {
+      return;
+    }
+
```
Comment (afd) [inline source/fuzz/fuzzer_pass_add_image_sample_unused_components.cpp:48]: The following looks very good.  However, it is intricate and will be hard to understand for someone who doesn't already know this instruction.

I suggest you add two worked examples, one where the existing type is int, the other where it is vec2 (i.e., a 2d floating point vector).  Then at each stage of the algorithm you show using psesudocode what would be computed in each case.

Take a look at what I've done in transformation_add_function.cpp from lines 586-614 - there are little snippets of illustrative SPIR-V.  I think something along those lines could be useful here.  It will be different as you'll be describing existing SPIR-V and the types that will be needed based on it.

File: source/fuzz/transformation_add_image_sample_unused_components.cpp [hunk 3]
```diff
@@ -0,0 +1,115 @@
...
+  auto coordinate_with_unused_components_instruction =
+      ir_context->get_def_use_mgr()->GetDef(
+          message_.coordinate_with_unused_components_id());
+
+  // The coordinate with unused components instruction must be defined.
+  if (coordinate_with_unused_components_instruction == nullptr) {
+    return false;
+  }
+
+  // It must be an OpCompositeConstruct instruction.
```
Comment (afd) [inline source/fuzz/transformation_add_image_sample_unused_components.cpp:74]: Am I correct that it doesn't have to be OpCompositeConstruct in order for the module to be valid, but rather we need it to be this instruction because we need to look inside the construction to check that the original components are there?  I think it would be good to clarify that slightly in the comment.

File: source/fuzz/transformation_add_image_sample_unused_components.cpp [hunk 4]
```diff
@@ -0,0 +1,115 @@
...
+  return true;
+}
+
+void TransformationAddImageSampleUnusedComponents::Apply(
+    opt::IRContext* ir_context, TransformationContext* /*unused*/) const {
+  // Sets the coordinate operand.
+  auto image_sample_instruction =
+      FindInstruction(message_.instruction_descriptor(), ir_context);
+  image_sample_instruction->SetInOperand(
+      1, {message_.coordinate_with_unused_components_id()});
```
Comment (afd) [inline source/fuzz/transformation_add_image_sample_unused_components.cpp:104]: After this we should invalidate analyses since the module has changed.  I recommend invalidating all analyses - as is done in most other transformations - out of caution.

File: source/fuzz/fuzzer_pass_add_image_sample_unused_components.cpp (hunk 1 above)
Comment (andreperezmaselco) [reply source/fuzz/fuzzer_pass_add_image_sample_unused_components.cpp:107]: Done.

File: source/fuzz/transformation_add_image_sample_unused_components.cpp (hunk 4 above)
Comment (andreperezmaselco) [reply source/fuzz/transformation_add_image_sample_unused_components.cpp:104]: Done.

File: source/fuzz/fuzzer_pass_add_image_sample_unused_components.cpp (hunk 2 above)
Comment (andreperezmaselco) [reply source/fuzz/fuzzer_pass_add_image_sample_unused_components.cpp:48]: Don't you think the comments explain by themselves?
I'm trying to explain with code, but I guess it is redundant.

File: source/fuzz/transformation_add_image_sample_unused_components.cpp (hunk 3 above)
Comment (andreperezmaselco) [reply source/fuzz/transformation_add_image_sample_unused_components.cpp:74]: Done.

File: source/fuzz/fuzzer_pass_add_image_sample_unused_components.cpp (hunk 2 above)
Comment (afd) [reply source/fuzz/fuzzer_pass_add_image_sample_unused_components.cpp:48]: For me, a worked example alongside the comments would be really useful.  The comments explain what the code does *in general*.   A worked example would show what the code does to a specific fragment of SPIR-V.  I think the two together would be great.

Can you have a go?

Comment (andreperezmaselco) [reply source/fuzz/fuzzer_pass_add_image_sample_unused_components.cpp:91]: Done.
