### PR TITLE
spirv-opt: Add LegalizeMultidimArrayPass

### LINKED ISSUE #7922: [SPIR-V] Arrays of arrays of resources are unsupported
**Description**
Using `RWTexture2D<float4>[16][32]` for example produces invalid SPIRV. Annotating this resource with `[[vk::image_format("unknown")]]` produces a validation error. It seems like this feature is unsupported, while with DXIL this works okay (though it flattens it to a 1D array).

**Steps to Reproduce**
```cpp
//dxc -spirv -E mainCompute -T cs_6_5
RWTexture2D<float4> _test[16][32];

[numthreads(8, 8, 1)]
void mainCompute(uint2 id : SV_DispatchThreadID) {
    _test[0][0][id] = float4(id, 0, 1);
}
```
```
fatal error: generated SPIR-V is invalid: [VUID-StandaloneSpirv-UniformConstant-04655] UniformConstant OpVariable <id> '4[%_test]' has illegal type.
Variables identified with the UniformConstant storage class are used only as handles to refer to opaque resources. Such variables must be typed as OpTypeImage, OpTypeSampler, OpTypeSampledImage, OpTypeAccelerationStructureKHR, or an array of one of these types.
  %_test = OpVariable %_ptr_UniformConstantarrarr_type_2d_image_uint_32_uint_16 UniformConstant

note: please file a bug report on https://github.com/Microsoft/DirectXShaderCompiler/issues with source code if possible
```

And
```cpp
[[vk::image_format("unknown")]] RWTexture2D<float4> _test[16][32];

[numthreads(8, 8, 1)]
void mainCompute(uint2 id : SV_DispatchThreadID) {
    _test[0][0][id] = float4(id, 0, 1);
}
```
```
C:\local\Temp\ea8c1737-a2f4-421d-a3b7-88e1c5278ee6.hlsl:2:3: error: 'image_format' attribute only applies to RWTextures, Buffers and RWBuffers
[[vk::image_format("unknown")]] RWTexture2D<float4> _test[16][32];
  ^
```

**Actual Behavior**
Spirv to support this with arrays of arrays (if possible by spec), otherwise flattening the array or throwing an error that's clearer about lack of multi dimensional descriptor array support.

**Environment**
- DXC version: latest
- Host Operating System: N/A

### PR DESCRIPTION
**Pull request by s-perron**
This pass transforms multidimensional arrays of resources (e.g.,
Texture2D g_Textures[2][3]) into single-dimensional arrays (e.g.,
Texture2D g_Textures[6]) and updates all access chains that reference
them.

This transformation is required for Vulkan compatibility, as multidimensional
resource arrays are not allowed in some storage classes.

Specifically, it helps avoid:
- VUID-StandaloneSpirv-Uniform-06807
- VUID-StandaloneSpirv-UniformConstant-04655

Fixes https://github.com/microsoft/DirectXShaderCompiler/issues/7922

### CODE REVIEW

File: include/spirv-tools/optimizer.hpp [hunk 1]
```diff
@@ -640,14 +640,12 @@ Optimizer::PassToken CreateLoopFusionPass(size_t max_registers_per_loop);
 Optimizer::PassToken CreateLoopPeelingPass();
 
 // Creates a loop unswitch pass.
-// This pass will look for loop independent branch conditions and move the
```
Comment (Keenuts) [inline include/spirv-tools/optimizer.hpp:643]: why remove those?

File: source/opt/legalize_multidim_array_pass.cpp [hunk 2]
```diff
@@ -0,0 +1,268 @@
...
+}
+
+void LegalizeMultidimArrayPass::GetArrayDimensions(uint32_t type_id,
+                                                   std::vector<uint32_t>* dims,
+                                                   uint32_t* element_type_id) {
+  Instruction* type_inst = context()->get_def_use_mgr()->GetDef(type_id);
+  while (type_inst->opcode() == spv::Op::OpTypeArray) {
+    uint32_t length_id = type_inst->GetSingleWordInOperand(1);
+    Instruction* length_inst = context()->get_def_use_mgr()->GetDef(length_id);
+    // Assume OpConstant for now.
```
Comment (Keenuts) [inline source/opt/legalize_multidim_array_pass.cpp]: altenative is OpSpecConstant? Should this be a FIXME with a issue #?

File: source/opt/legalize_multidim_array_pass.h [hunk 3]
```diff
@@ -0,0 +1,55 @@
...
+  bool RewriteAccessChains(Instruction* var, uint32_t old_ptr_type_id);
+
+  // Returns true if all uses of |var| can be legalized.
+  bool CanLegalize(Instruction* var);
+
+  // Recursively checks if the uses of |inst| can be legalized.
+  bool CheckUse(Instruction* inst, uint32_t max_depth);
+
+  // Returns the dimensions of the array type |type_id|.
+  void GetArrayDimensions(uint32_t type_id, std::vector<uint32_t>* dims,
```
Comment (Keenuts) [inline source/opt/legalize_multidim_array_pass.h:48]: I would either say the function required the `dims` array to be empty, or add a `dims.clear()` in the `GetArrayDimentions` body.

File: source/opt/legalize_multidim_array_pass.cpp [hunk 4]
```diff
@@ -0,0 +1,268 @@
...
+  // Create new OpTypePointer.
+  spv::StorageClass sc =
+      static_cast<spv::StorageClass>(ptr_type_inst->GetSingleWordInOperand(0));
+  analysis::Pointer new_ptr_type(type_mgr->GetType(new_array_type_id), sc);
+  uint32_t new_ptr_type_id = type_mgr->GetTypeInstruction(&new_ptr_type);
+
+  var->SetResultType(new_ptr_type_id);
+  context()->UpdateDefUse(var);
+
+  // Move the var after the new pointer type to avoid a def-before-use.
```
Comment (Keenuts) [inline source/opt/legalize_multidim_array_pass.cpp:129]: Seems like the Process/CanLegalize doesn't check the storage class. This means the OpVariable storage class could be Function. If you put the type definition before you now put the type in the wrong module section no?

File: source/opt/legalize_multidim_array_pass.cpp [hunk 5]
```diff
@@ -0,0 +1,268 @@
...
+  }
+  return true;
+}
+
+bool LegalizeMultidimArrayPass::CheckUse(Instruction* inst,
+                                         uint32_t max_depth) {
+  if (inst->opcode() == spv::Op::OpAccessChain ||
+      inst->opcode() == spv::Op::OpInBoundsAccessChain) {
+    uint32_t num_indices = inst->NumInOperands() - 1;
+    return num_indices >= max_depth;
```
Comment (Keenuts) [inline source/opt/legalize_multidim_array_pass.cpp:240]: so if I follow, if we have:
```
tmp[2][2]
OpAccessChain %tmp %uint_0 %uint 0
```
we will flatten, but if we have:

```
tmp[2][2]
%a = OpAccessChain %tmp %uint_0
OpAccessChain %a %uint_0
```
Then we won't?

File: source/opt/legalize_multidim_array_pass.cpp [hunk 6]
```diff
@@ -0,0 +1,268 @@
...
+  Instruction* old_ptr_type_inst =
+      context()->get_def_use_mgr()->GetDef(old_ptr_type_id);
+  uint32_t old_pointee_type_id = old_ptr_type_inst->GetSingleWordInOperand(1);
+  std::vector<uint32_t> dims;
+  uint32_t element_type_id = 0;
+  GetArrayDimensions(old_pointee_type_id, &dims, &element_type_id);
+
+  // Calculate strides once
+  std::vector<uint32_t> strides(dims.size());
+  strides[dims.size() - 1] = 1;
```
Comment (Keenuts) [inline source/opt/legalize_multidim_array_pass.cpp:156]: This function is called with an array which passed `isMultiDim` earlied in the logic so OK, but please assert `dims.size() > 0` (and even > 1 here) before. Otherwise the constraint is very far to not miss it.

File: include/spirv-tools/optimizer.hpp (hunk 1 above)
Comment (s-perron) [reply include/spirv-tools/optimizer.hpp:643]: Cut-copy-paste issue. I'll put it back in and add more comments for the new pass.

File: source/opt/legalize_multidim_array_pass.cpp (hunk 2 above)
Comment (s-perron) [reply source/opt/legalize_multidim_array_pass.cpp]: Yes, the array length could be a spec constant. We could create and issue, but I have no intention of fixing it up. DXC never generates an array with a spec constant size, and GLSL does not have to get multi dimensional array legalized. I don't know what slang might do.

File: source/opt/legalize_multidim_array_pass.cpp (hunk 4 above)
Comment (s-perron) [reply source/opt/legalize_multidim_array_pass.cpp:129]: It is there implicitly. In `LegalizeMultidimArrayPass::IsMultidimArrayOfResources`, we call `descsroautil::IsDescriptorArray`, which return true only if the array has the set and binding decorations. That cannot happen if it is in the function scope.

This pass is assuming that is it run late in the legazlier phase, and private and function scope resource arrays have been optimized away. This simplifies the pass significantly.

File: source/opt/legalize_multidim_array_pass.cpp (hunk 5 above)
Comment (s-perron) [reply source/opt/legalize_multidim_array_pass.cpp:240]: That is correct. We run the CombineAccessChains pass just before so that we can reduce the number of cases we have to consider.

In practice, the second case will get turned into the first case before reaching this pass.

File: source/opt/legalize_multidim_array_pass.cpp (hunk 2 above)
Comment (s-perron) [reply source/opt/legalize_multidim_array_pass.cpp]: I added a comment explaining why I do not handle OpSpecConstant, and I do not make it seem like we intend on handling it in the future.

File: source/opt/legalize_multidim_array_pass.h (hunk 3 above)
Comment (s-perron) [reply source/opt/legalize_multidim_array_pass.h:48]: I added the clear, and an assert that Dim is not nullptr.  It is annoying. The google style guide to to be to use a pointer for output parameter and const& for input parameters. That is what we did through spir-v tools, but that has since changed. I don't know which one is best to use.

File: source/opt/legalize_multidim_array_pass.cpp (hunk 6 above)
Comment (s-perron) [reply source/opt/legalize_multidim_array_pass.cpp:156]: done.

File: source/opt/legalize_multidim_array_pass.cpp (hunk 5 above)
Comment (s-perron) [reply source/opt/legalize_multidim_array_pass.cpp:240]: I added comment to the documentation the combine access chains should be run before this pass.

**Review by Keenuts — APPROVED** [review]

**Comment by s-perron** [comment]
The failing macos test are an infrastructure issue not related to this change. Still fails even if I rerun. The smoke test failure is related to this change. DXC tests will have to be updated now that we run the combine access chain pass.
