### PR TITLE
Fix merge return in the face of breaks

### LINKED ISSUE #2453: spirv-opt generates code that spirv-val rejects: ID ... defined in block ... does not dominate its us e in block ...
[Files to reproduce problem](https://github.com/KhronosGroup/SPIRV-Tools/files/2968969/to_file2.zip)

glsl_reduced.frag is a minimized GLSL shader.  When compiled to SPIR-V with glslangValidator we get glsl_reduced.spv.  This has been further reduced using spirv-reduce to spiv_reduced.spv.

Doing:

spirv-opt spirv_reduced.spv --inline-entry-points-exhaustive --private-to-local 
--ccp --merge-blocks --eliminate-dead-branches --eliminate-dead-branches --combi
ne-access-chains --reduce-load-size --redundancy-elimination --convert-local-acc
ess-chains --convert-local-access-chains --eliminate-dead-inserts --private-to-l
ocal --reduce-load-size --ccp --eliminate-dead-branches --merge-return --elimina
te-dead-inserts --eliminate-local-multi-store --inline-entry-points-exhaustive -
-eliminate-dead-branches --eliminate-dead-code-aggressive --eliminate-local-sing
le-store --eliminate-local-multi-store --reduce-load-size --inline-entry-points-
exhaustive --copy-propagate-arrays --if-conversion --simplify-instructions --ccp
 --eliminate-local-multi-store -o temp.spv
spirv-val temp.spv

should trigger the problem:

error: line 71: ID 144[%144] defined in block 142[%142] does not dominate its us
e in block 152[%152]
  %152 = OpLabel

I did not try to reduce the spirv-opt flags, in case (as with #2450) there may be an issue both with the optimizer generating invalid code and the validator not picking this up soon enough.

Found using [GraphicsFuzz](http://github.com/google/graphicsfuzz)

### PR DESCRIPTION
**Pull request by alan-baker**
Fixes #2453

* Enable addition of OpPhi instructions when the loop has multiple
predecessors of the merge due to a break
 * This can result in some values no longer dominating their uses
* Track return blocks in structured flow to produce OpPhis that have
multiple undef and non-undef arguments
* New tests to catch the bug

### CODE REVIEW

**Comment by alan-baker** [comment]
Linker crashed, seems unrelated to my change.

File: source/opt/merge_return_pass.cpp [hunk 1]
```diff
@@ -232,11 +233,19 @@ void MergeReturnPass::UpdatePhiNodes(BasicBlock* new_source,
...
   if (target_pred.size() == 1) {
     MarkForNewPhiNodes(target, context()->get_instr_block(target_pred[0]));
+  } else {
+    // If the loop contained a break and a return, OpPhi instructions may be
+    // required starting from the dominator of the loop merge.
+    DominatorAnalysis* dom_tree =
+        context()->GetDominatorAnalysis(target->GetParent());
+    auto idom = dom_tree->ImmediateDominator(target);
+    if (idom) {
+      MarkForNewPhiNodes(target, idom);
```
Comment (s-perron) [inline source/opt/merge_return_pass.cpp]: If the header is available here, we could check it only if `idom` is not the header for the merge block.  If it is not available, then this is fine.  The search will be short anyway.
